import type { Audience, ThemeId } from './types'
import { clusteredObstacleRoomIndex } from './spatialPlan'

export interface ThemeCharacter {
  readonly name: string
  readonly emoji: string
  readonly description: string
}

export interface ThemeItem {
  readonly label: string
  readonly emoji: string
}

export interface Theme {
  readonly id: ThemeId
  readonly audience?: Audience
  readonly title: string
  readonly introductions: readonly string[]
  readonly objectives: readonly string[]
  readonly places: readonly string[]
  readonly characters: readonly ThemeCharacter[]
  readonly items: readonly ThemeItem[]
  readonly roomObjects?: readonly ThemeItem[]
  readonly roomObjectsByPlace?: readonly (readonly ThemeItem[])[]
  readonly terrainFeature?: {
    readonly kind: 'pond'
    readonly placeIndex: number
  }
  readonly victories: readonly string[]
}

const sharedNames = [
  ['Aina', '🦊', 'una guineu curiosa'],
  ['Biel', '🐻', 'un os amable'],
  ['Cora', '🐰', 'una conilla riallera'],
  ['Duna', '🦉', 'una òliba observadora'],
  ['Èric', '🐸', 'una granota saltadora'],
  ['Fina', '🐼', 'una panda creativa'],
  ['Gala', '🦋', 'una papallona brillant'],
  ['Hugo', '🐢', 'una tortuga tranquil·la'],
] as const

const makeCharacters = (emojiOverrides: readonly string[]): readonly ThemeCharacter[] =>
  sharedNames.map(([name, emoji, description], index) => ({
    name,
    emoji: emojiOverrides[index] ?? emoji,
    description,
  }))

const makePeople = (
  entries: readonly (readonly [string, string])[],
): readonly ThemeCharacter[] =>
  entries.map(([name, emoji]) => ({ name, emoji, description: 'una persona del grup' }))

const makeItems = (entries: readonly (readonly [string, string])[]): readonly ThemeItem[] =>
  entries.map(([label, emoji]) => ({ label, emoji }))

const roomObjectCatalog = {
  music: makeItems([
    ['micròfon de peu', '🎙️'],
    ['mesclador', '🎚️'],
    ['taula de control', '🎛️'],
    ['altaveu', '🔊'],
    ['auriculars', '🎧'],
    ['teclat', '🎹'],
    ['tambor', '🥁'],
    ['guitarra', '🎸'],
    ['saxòfon', '🎷'],
    ['violí', '🎻'],
    ['cadira', '🪑'],
    ['llum de taula', '💡'],
    ['armari', '🗄️'],
    ['caixa d’eines', '🧰'],
    ['bloc de notes', '📝'],
    ['partitura', '🎼'],
    ['ordinador', '💻'],
    ['temporitzador', '⏱️'],
    ['endoll', '🔌'],
    ['got d’aigua', '🥤'],
  ]),
  sports: makeItems([
    ['pilota de bàsquet', '🏀'],
    ['pilota de futbol', '⚽'],
    ['pilota de voleibol', '🏐'],
    ['disc', '🥏'],
    ['raqueta de taula', '🏓'],
    ['porteria', '🥅'],
    ['patí', '🛹'],
    ['bicicleta', '🚲'],
    ['banc', '🪑'],
    ['font d’aigua', '🚰'],
    ['cronòmetre', '⏱️'],
    ['megàfon', '📣'],
    ['samarreta', '🎽'],
    ['banderí', '⛳'],
    ['cistella', '🧺'],
    ['ampolla', '🧴'],
    ['bossa d’equip', '🎒'],
    ['escala', '🪜'],
    ['trofeu', '🏆'],
    ['medalla', '🥇'],
  ]),
  creative: makeItems([
    ['pantalla', '🖥️'],
    ['impressora', '🖨️'],
    ['càmera', '📷'],
    ['llum de treball', '💡'],
    ['cadira', '🪑'],
    ['caixa d’eines', '🧰'],
    ['escaire', '📐'],
    ['regle', '📏'],
    ['paleta de color', '🎨'],
    ['rodet de fil', '🧵'],
    ['cabdell', '🧶'],
    ['xinxeta', '📌'],
    ['armari', '🗄️'],
    ['llibres', '📚'],
    ['bloc d’esbossos', '📝'],
    ['marc', '🖼️'],
    ['maqueta', '🧩'],
    ['portàtil', '💻'],
    ['mirall', '🪞'],
    ['caixa', '📦'],
  ]),
  books: makeItems([
    ['cadira', '🪑'],
    ['sofà', '🛋️'],
    ['planta', '🪴'],
    ['llum de lectura', '💡'],
    ['llibres', '📚'],
    ['tassa', '☕'],
    ['tetera', '🫖'],
    ['rellotge', '🕰️'],
    ['armari', '🗄️'],
    ['diari', '📰'],
    ['quadre', '🖼️'],
    ['cistella', '🧺'],
    ['revister', '🗂️'],
    ['llibre obert', '📖'],
    ['quadern', '📝'],
    ['finestra', '🪟'],
    ['porta', '🚪'],
    ['caixa', '📦'],
    ['mirall', '🪞'],
    ['paraigüer', '🌂'],
  ]),
  garden: makeItems([
    ['test', '🪴'],
    ['cistell', '🧺'],
    ['galleda', '🪣'],
    ['tanca baixa', '🚧'],
    ['fusta', '🪵'],
    ['pedra', '🪨'],
    ['caixa d’eines', '🧰'],
    ['planter', '🌱'],
    ['cartell', '🪧'],
    ['aixeta', '🚰'],
    ['carretó', '🛒'],
    ['gira-sol', '🌻'],
    ['tomàquet', '🍅'],
    ['pastanaga', '🥕'],
    ['pèsols', '🫛'],
    ['maó', '🧱'],
    ['escala', '🪜'],
    ['escombra', '🧹'],
    ['esponja', '🧽'],
    ['gerro', '🏺'],
    ['nenúfar', '🪷'],
    ['gota d’aigua', '💧'],
    ['granota', '🐸'],
    ['ànec', '🦆'],
    ['fulles seques', '🍂'],
    ['cuc de terra', '🪱'],
  ]),
  market: makeItems([
    ['cistella', '🧺'],
    ['balança', '⚖️'],
    ['carretó', '🛒'],
    ['rebut', '🧾'],
    ['caixa', '📦'],
    ['cartell', '🪧'],
    ['formatge', '🧀'],
    ['pa', '🥖'],
    ['ram', '💐'],
    ['tassa', '☕'],
    ['pot', '🫙'],
    ['bossa', '🛍️'],
    ['pera', '🍐'],
    ['poma', '🍎'],
    ['pastanaga', '🥕'],
    ['tetera', '🫖'],
    ['gerro', '🏺'],
    ['cadira', '🪑'],
    ['esponja', '🧽'],
    ['escombra', '🧹'],
  ]),
} as const

const roomObjectsFor = (
  catalog: readonly ThemeItem[],
  labels: readonly string[],
): readonly ThemeItem[] =>
  labels.map((label) => {
    const item = catalog.find((candidate) => candidate.label === label)
    if (!item) throw new Error(`Objecte d’estança desconegut: ${label}`)
    return item
  })

const musicRoomObjectsByPlace: readonly (readonly ThemeItem[])[] = [
  roomObjectsFor(roomObjectCatalog.music, [
    'micròfon de peu',
    'auriculars',
    'partitura',
    'cadira',
    'llum de taula',
  ]),
  roomObjectsFor(roomObjectCatalog.music, [
    'saxòfon',
    'violí',
    'auriculars',
    'cadira',
    'got d’aigua',
  ]),
  roomObjectsFor(roomObjectCatalog.music, [
    'mesclador',
    'taula de control',
    'altaveu',
    'ordinador',
    'endoll',
  ]),
  roomObjectsFor(roomObjectCatalog.music, [
    'teclat',
    'altaveu',
    'cadira',
    'bloc de notes',
    'temporitzador',
  ]),
  roomObjectsFor(roomObjectCatalog.music, [
    'armari',
    'caixa d’eines',
    'bloc de notes',
    'partitura',
    'llum de taula',
  ]),
  roomObjectsFor(roomObjectCatalog.music, [
    'tambor',
    'guitarra',
    'saxòfon',
    'violí',
    'altaveu',
  ]),
]

const sportsRoomObjectsByPlace: readonly (readonly ThemeItem[])[] = [
  roomObjectsFor(roomObjectCatalog.sports, [
    'pilota de bàsquet',
    'pilota de voleibol',
    'porteria',
    'banc',
    'banderí',
  ]),
  roomObjectsFor(roomObjectCatalog.sports, [
    'pilota de futbol',
    'raqueta de taula',
    'disc',
    'banc',
    'banderí',
  ]),
  roomObjectsFor(roomObjectCatalog.sports, [
    'escala',
    'banc',
    'font d’aigua',
    'bossa d’equip',
    'banderí',
  ]),
  roomObjectsFor(roomObjectCatalog.sports, [
    'samarreta',
    'ampolla',
    'bossa d’equip',
    'banc',
    'font d’aigua',
  ]),
  roomObjectsFor(roomObjectCatalog.sports, [
    'cronòmetre',
    'megàfon',
    'trofeu',
    'medalla',
    'banderí',
    'cistella',
  ]),
  roomObjectsFor(roomObjectCatalog.sports, ['patí', 'bicicleta', 'disc', 'porteria', 'escala']),
]

const creativeRoomObjectsByPlace: readonly (readonly ThemeItem[])[] = [
  roomObjectsFor(roomObjectCatalog.creative, [
    'pantalla',
    'cadira',
    'regle',
    'escaire',
    'bloc d’esbossos',
  ]),
  roomObjectsFor(roomObjectCatalog.creative, [
    'xinxeta',
    'marc',
    'llibres',
    'maqueta',
    'paleta de color',
  ]),
  roomObjectsFor(roomObjectCatalog.creative, [
    'paleta de color',
    'rodet de fil',
    'cabdell',
    'armari',
    'caixa',
  ]),
  roomObjectsFor(roomObjectCatalog.creative, [
    'càmera',
    'llum de treball',
    'portàtil',
    'mirall',
    'pantalla',
  ]),
  roomObjectsFor(roomObjectCatalog.creative, [
    'impressora',
    'portàtil',
    'caixa',
    'armari',
    'caixa d’eines',
  ]),
  roomObjectsFor(roomObjectCatalog.creative, [
    'maqueta',
    'escaire',
    'regle',
    'caixa d’eines',
    'cadira',
  ]),
]

const bookRoomObjectsByPlace: readonly (readonly ThemeItem[])[] = [
  roomObjectsFor(roomObjectCatalog.books, [
    'cadira',
    'tassa',
    'tetera',
    'llibre obert',
    'quadern',
  ]),
  roomObjectsFor(roomObjectCatalog.books, [
    'sofà',
    'llum de lectura',
    'llibres',
    'tassa',
    'planta',
  ]),
  roomObjectsFor(roomObjectCatalog.books, [
    'finestra',
    'porta',
    'planta',
    'quadre',
    'cadira',
    'paraigüer',
  ]),
  roomObjectsFor(roomObjectCatalog.books, [
    'llibres',
    'armari',
    'revister',
    'llibre obert',
    'cistella',
  ]),
  roomObjectsFor(roomObjectCatalog.books, ['tassa', 'tetera', 'diari', 'rellotge', 'quadern']),
  roomObjectsFor(roomObjectCatalog.books, [
    'sofà',
    'mirall',
    'llum de lectura',
    'planta',
    'caixa',
  ]),
]

const gardenRoomObjectsByPlace: readonly (readonly ThemeItem[])[] = [
  roomObjectsFor(roomObjectCatalog.garden, [
    'test',
    'planter',
    'tomàquet',
    'pastanaga',
    'pèsols',
    'galleda',
  ]),
  roomObjectsFor(roomObjectCatalog.garden, ['cistell', 'caixa d’eines', 'cartell', 'gerro']),
  roomObjectsFor(roomObjectCatalog.garden, ['fusta', 'maó', 'esponja', 'carretó']),
  roomObjectsFor(roomObjectCatalog.garden, ['gira-sol', 'escala', 'tanca baixa', 'aixeta']),
  roomObjectsFor(roomObjectCatalog.garden, ['nenúfar', 'gota d’aigua', 'granota', 'ànec']),
  roomObjectsFor(roomObjectCatalog.garden, [
    'fulles seques',
    'cuc de terra',
    'escombra',
    'pedra',
  ]),
]

const marketRoomObjectsByPlace: readonly (readonly ThemeItem[])[] = [
  roomObjectsFor(roomObjectCatalog.market, ['pa', 'cistella', 'balança', 'carretó', 'cartell']),
  roomObjectsFor(roomObjectCatalog.market, [
    'pera',
    'poma',
    'pastanaga',
    'cistella',
    'carretó',
  ]),
  roomObjectsFor(roomObjectCatalog.market, ['ram', 'gerro', 'esponja', 'cistella', 'cartell']),
  roomObjectsFor(roomObjectCatalog.market, ['tassa', 'tetera', 'pot', 'cadira', 'cartell']),
  roomObjectsFor(roomObjectCatalog.market, [
    'pot',
    'gerro',
    'esponja',
    'escombra',
    'caixa',
    'rebut',
  ]),
  roomObjectsFor(roomObjectCatalog.market, [
    'formatge',
    'balança',
    'cistella',
    'bossa',
    'rebut',
  ]),
]

export const themes: readonly Theme[] = [
  {
    id: 'forest-party',
    title: 'La festa del bosc',
    introductions: ['Al bosc ja està tot preparat per a una festa plena de colors.'],
    objectives: ['Ajuda cada amic a trobar el seu racó de la festa.'],
    places: [
      'La clariana',
      'L’arbre gran',
      'El pont de fusta',
      'El jardí de flors',
      'La cabana',
      'El rierol',
      'La roca rodona',
      'La praderia',
    ],
    characters: makeCharacters(['🦊', '🐻', '🐰', '🦉', '🐸', '🐼', '🦋', '🐢']),
    items: [
      ['galeta', '🍪'],
      ['flor', '🌼'],
      ['globus', '🎈'],
      ['barret', '🎩'],
      ['poma', '🍎'],
      ['llibre', '📘'],
      ['estrella', '⭐'],
      ['fulla', '🍃'],
    ].map(([label, emoji]) => ({ label, emoji })),
    victories: ['Quina festa més ben organitzada!'],
  },
  {
    id: 'treasure-island',
    title: 'L’illa de les sorpreses',
    introductions: ['Una illa assolellada guarda petits regals per compartir.'],
    objectives: ['Descobreix on espera cada explorador amable.'],
    places: [
      'La platja suau',
      'La palmera',
      'La cova de petxines',
      'El far',
      'El moll',
      'La duna daurada',
      'La llacuna',
      'El mirador',
    ],
    characters: makeCharacters(['🦜', '🐬', '🦀', '🐢', '🐠', '🦭', '🐙', '🐳']),
    items: [
      ['petxina', '🐚'],
      ['mapa', '🗺️'],
      ['pinya', '🍍'],
      ['banderí', '🚩'],
      ['sol', '☀️'],
      ['cubell', '🪣'],
      ['corall', '🪸'],
      ['barqueta', '⛵'],
    ].map(([label, emoji]) => ({ label, emoji })),
    victories: ['Totes les sorpreses han trobat el seu lloc!'],
  },
  {
    id: 'kind-magic-school',
    title: 'L’escola de màgia amable',
    introductions: ['A l’escola, la màgia serveix per fer créixer flors i somriures.'],
    objectives: ['Ordena els aprenents als seus espais preferits.'],
    places: [
      'La biblioteca',
      'L’aula d’estrelles',
      'El pati',
      'La torre',
      'El taller',
      'L’hivernacle',
      'La sala de música',
      'El passadís arc de Sant Martí',
    ],
    characters: makeCharacters(['🧙', '🧚', '🧝', '🦄', '🐱', '🦉', '🐇', '🐲']),
    items: [
      ['vareta de flors', '🌷'],
      ['poció de bombolles', '🫧'],
      ['llibre de contes', '📕'],
      ['estrella', '🌟'],
      ['capa', '🧣'],
      ['clau daurada', '🗝️'],
      ['ploma', '🪶'],
      ['cristall', '🔮'],
    ].map(([label, emoji]) => ({ label, emoji })),
    victories: ['La màgia amable ho ha deixat tot a punt!'],
  },
  {
    id: 'space-trip',
    title: 'Viatge per l’espai',
    introductions: ['La tripulació visita planetes plens de formes i melodies.'],
    objectives: ['Troba l’estació perfecta per a cada viatger.'],
    places: [
      'El planeta blau',
      'L’estació musical',
      'La lluna petita',
      'El jardí estel·lar',
      'El coet',
      'L’observatori',
      'El núvol còsmic',
      'L’anella brillant',
    ],
    characters: makeCharacters(['👩‍🚀', '🤖', '👾', '🛸', '🐙', '🦊', '🐻', '🐰']),
    items: [
      ['coet petit', '🚀'],
      ['planeta', '🪐'],
      ['estrella', '⭐'],
      ['satèl·lit', '🛰️'],
      ['flor lunar', '🌙'],
      ['comandament', '🎛️'],
      ['cometa', '☄️'],
      ['auriculars', '🎧'],
    ].map(([label, emoji]) => ({ label, emoji })),
    victories: ['La tripulació ja pot continuar la seva aventura!'],
  },
  {
    id: 'fun-farm',
    title: 'La granja divertida',
    introductions: ['A la granja hi ha un munt de feines agradables per repartir.'],
    objectives: ['Acompanya cada animal al seu racó.'],
    places: [
      'L’hort',
      'El paller',
      'L’estable',
      'El pomer',
      'La bassa',
      'El molí',
      'La tanca blava',
      'La caseta',
    ],
    characters: makeCharacters(['🐮', '🐷', '🐔', '🐑', '🐴', '🦆', '🐐', '🐇']),
    items: [
      ['pastanaga', '🥕'],
      ['blat', '🌾'],
      ['llet', '🥛'],
      ['poma', '🍏'],
      ['regadora', '🪴'],
      ['cistell', '🧺'],
      ['flor', '🌻'],
      ['campaneta', '🔔'],
    ].map(([label, emoji]) => ({ label, emoji })),
    victories: ['La granja està plena d’alegria!'],
  },
  {
    id: 'sea-garden',
    title: 'El jardí marí',
    introductions: ['Sota el mar, els amics preparen una dansa de bombolles.'],
    objectives: ['Col·loca cada amic marí al seu espai de colors.'],
    places: [
      'El corall rosa',
      'La cova blava',
      'L’alguer',
      'La petxina gran',
      'La roca cantant',
      'El jardí de perles',
      'La bombolla gegant',
      'El sorral',
    ],
    characters: makeCharacters(['🐠', '🐙', '🦀', '🐬', '🐳', '🦭', '🐡', '🦑']),
    items: [
      ['perla', '🫧'],
      ['petxina', '🐚'],
      ['corall', '🪸'],
      ['alga', '🌿'],
      ['estrella marina', '⭐'],
      ['peixet', '🐟'],
      ['bombolla', '🫧'],
      ['corona', '👑'],
    ].map(([label, emoji]) => ({ label, emoji })),
    victories: ['La dansa marina ja pot començar!'],
  },
  {
    id: 'dino-park',
    title: 'El parc de dinosaures simpàtics',
    introductions: ['Els dinosaures del parc preparen una excursió tranquil·la.'],
    objectives: ['Ajuda cada dinosaure a trobar la seva parada.'],
    places: [
      'El niu de fulles',
      'El llac',
      'La roca alta',
      'El bosc de falgueres',
      'La vall',
      'El pont',
      'La font',
      'El turó',
    ],
    characters: makeCharacters(['🦕', '🦖', '🐢', '🦜', '🐘', '🦒', '🐊', '🦛']),
    items: [
      ['fulla', '🍃'],
      ['petjada', '👣'],
      ['poma', '🍎'],
      ['motxilla', '🎒'],
      ['flor', '🌺'],
      ['prismàtics', '🔭'],
      ['pedreta', '🪨'],
      ['sol', '☀️'],
    ].map(([label, emoji]) => ({ label, emoji })),
    victories: ['El parc està llest per a l’excursió!'],
  },
  {
    id: 'friendly-monster-town',
    title: 'El poble de monstres amistosos',
    introductions: ['Al poble, tothom ajuda a decorar la plaça.'],
    objectives: ['Troba la casella de cada veí amistós.'],
    places: [
      'La plaça',
      'La fleca',
      'El taller',
      'La font',
      'El cinema',
      'La biblioteca',
      'El jardí',
      'La caseta groga',
    ],
    characters: makeCharacters(['👾', '🤖', '👽', '🧌', '🦄', '🐲', '🧸', '🐱']),
    items: [
      ['banderí', '🎏'],
      ['pastís', '🍰'],
      ['flor', '🌸'],
      ['pintura', '🎨'],
      ['música', '🎵'],
      ['llibre', '📚'],
      ['globus', '🎈'],
      ['galeta', '🍪'],
    ].map(([label, emoji]) => ({ label, emoji })),
    victories: ['La plaça ha quedat preciosa!'],
  },
  {
    id: 'color-fair',
    title: 'La fira de colors',
    introductions: ['La fira té jocs suaus, música i moltes banderoles.'],
    objectives: ['Reparteix els amics per les parades de la fira.'],
    places: [
      'La roda de colors',
      'La parada groga',
      'El teatre',
      'El jardí de globus',
      'La carpa',
      'El carrusel',
      'El racó de contes',
      'La fonteta',
    ],
    characters: makeCharacters(['🦋', '🐝', '🦊', '🐰', '🐼', '🐸', '🐻', '🦉']),
    items: [
      ['globus', '🎈'],
      ['entrada', '🎟️'],
      ['pinzell', '🖌️'],
      ['flor', '🌼'],
      ['cor', '💛'],
      ['cinta', '🎀'],
      ['conte', '📗'],
      ['estrella', '✨'],
    ].map(([label, emoji]) => ({ label, emoji })),
    victories: ['La fira és un arc de Sant Martí d’alegria!'],
  },
  {
    id: 'mountain-trip',
    title: 'Excursió a la muntanya',
    introductions: ['Un grup d’amics surt a observar núvols, flors i panoràmiques.'],
    objectives: ['Ajuda cada excursionista a trobar la seva parada.'],
    places: [
      'El refugi',
      'El mirador',
      'El prat',
      'La cascada suau',
      'El bosc',
      'El pontet',
      'La cova de colors',
      'El cim',
    ],
    characters: makeCharacters(['🦌', '🐿️', '🦉', '🦊', '🐻', '🐐', '🦋', '🐇']),
    items: [
      ['motxilla', '🎒'],
      ['cantimplora', '💧'],
      ['flor', '🌷'],
      ['fulla', '🍂'],
      ['prismàtics', '🔭'],
      ['mapa', '🗺️'],
      ['barret', '🧢'],
      ['poma', '🍏'],
    ].map(([label, emoji]) => ({ label, emoji })),
    victories: ['Quina excursió tan ben pensada!'],
  },
  {
    id: 'music-studio',
    audience: 'teens',
    title: 'L’estudi de música',
    introductions: ['L’estudi té llums, ritmes i idees per ordenar.'],
    objectives: ['Troba l’espai de cada persona abans de la sessió.'],
    places: [
      'La cabina 1',
      'La cabina 2',
      'La taula de mescles',
      'El teclat',
      'El mural de pòsters',
      'La sala d’assaig',
      'El racó del baix',
      'El sofà blau',
    ],
    characters: makePeople([
      ['Alex', '🧑🏻‍🦱'],
      ['Berta', '👩🏽'],
      ['Casey', '🧑🏾'],
      ['Dani', '👨🏻'],
      ['Eli', '🧑🏼'],
      ['Fran', '👨🏽‍🦱'],
      ['Gina', '👩🏾‍🦱'],
      ['Kai', '🧑🏻‍🦰'],
    ]),
    items: makeItems([
      ['acreditació', '🪪'],
      ['mòbil', '📱'],
      ['gorra', '🧢'],
      ['jaqueta', '🧥'],
      ['ulleres', '👓'],
      ['rellotge', '⌚'],
      ['motxilla', '🎒'],
      ['carpeta', '📁'],
    ]),
    roomObjects: roomObjectCatalog.music,
    roomObjectsByPlace: musicRoomObjectsByPlace,
    victories: ['La sessió ja està a punt!'],
  },
  {
    id: 'sports-festival',
    audience: 'teens',
    title: 'El festival d’esports',
    introductions: ['El recinte obre amb proves, equips i molt bon ambient.'],
    objectives: ['Organitza les persones als espais del festival.'],
    places: [
      'La pista verda',
      'La pista blava',
      'El mur d’escalada',
      'La zona d’estiraments',
      'La taula de marques',
      'El circuit',
      'La grada',
      'El punt d’aigua',
    ],
    characters: makePeople([
      ['Ari', '🧑🏼‍🦱'],
      ['Blai', '👨🏽'],
      ['Clara', '👩🏻'],
      ['Dídac', '👨🏻‍🦰'],
      ['Emma', '👩🏾'],
      ['Fèlix', '👨🏼‍🦱'],
      ['Gala', '👩🏽‍🦱'],
      ['Nil', '👨🏾'],
    ]),
    items: makeItems([
      ['dorsal', '🔢'],
      ['casc', '⛑️'],
      ['mocador', '🧣'],
      ['gorra', '🧢'],
      ['rellotge', '⌚'],
      ['sabatilles', '👟'],
      ['acreditació', '🪪'],
      ['jaqueta', '🧥'],
    ]),
    roomObjects: roomObjectCatalog.sports,
    roomObjectsByPlace: sportsRoomObjectsByPlace,
    victories: ['El festival funciona de meravella!'],
  },
  {
    id: 'creative-lab',
    audience: 'teens',
    title: 'El laboratori creatiu',
    introductions: ['Al laboratori, cada idea troba una forma nova.'],
    objectives: ['Relaciona cada creador amb el seu espai.'],
    places: [
      'La taula de disseny',
      'La paret d’idees',
      'L’estació de color',
      'El racó de vídeo',
      'La impressora',
      'La taula de maquetes',
      'El sofà de prova',
      'La finestra gran',
    ],
    characters: makePeople([
      ['Aina', '👩🏻‍🦱'],
      ['Biel', '👨🏼'],
      ['Cora', '👩🏽'],
      ['Duna', '👩🏼‍🦰'],
      ['Èric', '👨🏾'],
      ['Fina', '👩🏾‍🦱'],
      ['Hugo', '👨🏻‍🦱'],
      ['Iris', '👩🏼'],
    ]),
    items: makeItems([
      ['acreditació', '🪪'],
      ['mòbil', '📱'],
      ['llapis', '✏️'],
      ['goma', '🧽'],
      ['carpeta', '📁'],
      ['portafolis', '💼'],
      ['retolador', '🖊️'],
      ['cinta', '🎀'],
    ]),
    roomObjects: roomObjectCatalog.creative,
    roomObjectsByPlace: creativeRoomObjectsByPlace,
    victories: ['Totes les idees tenen el seu lloc!'],
  },
  {
    id: 'book-club',
    audience: 'adults',
    title: 'El club de lectures',
    introductions: ['El club prepara una trobada amb llibres i converses.'],
    objectives: ['Troba la cadira de cada participant.'],
    places: [
      'La taula rodona',
      'La butaca verda',
      'El finestral',
      'La prestatgeria',
      'La taula petita',
      'El racó tranquil',
      'La llum de peu',
      'La cafetera',
    ],
    characters: makePeople([
      ['Alba', '👩🏻'],
      ['Bruno', '👨🏽'],
      ['Carme', '👩🏼‍🦳'],
      ['Dídac', '👨🏻‍🦰'],
      ['Elena', '👩🏾'],
      ['Ferran', '👨🏼‍🦱'],
      ['Gemma', '👩🏽‍🦱'],
      ['Joan', '👨🏾‍🦳'],
    ]),
    items: makeItems([
      ['novel·la', '📘'],
      ['punt de llibre', '🔖'],
      ['quadern', '📓'],
      ['ploma', '🖋️'],
      ['ulleres', '👓'],
      ['fullet', '🗒️'],
      ['bossa', '👜'],
      ['mòbil', '📱'],
    ]),
    roomObjects: roomObjectCatalog.books,
    roomObjectsByPlace: bookRoomObjectsByPlace,
    victories: ['La trobada ja pot començar!'],
  },
  {
    id: 'city-garden',
    audience: 'adults',
    title: 'El jardí de barri',
    introductions: ['El jardí compartit s’omple de mans i de colors.'],
    objectives: ['Situa cada veí al seu espai de feina.'],
    places: [
      'L’hort alt',
      'La taula de llavors',
      'El banc llarg',
      'La pèrgola',
      'La vora de la bassa',
      'El compostador',
      'La taula d’eines',
      'La porta blava',
    ],
    characters: makePeople([
      ['Anna', '👩🏻‍🦱'],
      ['Berta', '👩🏽'],
      ['Cesc', '👨🏼'],
      ['Dora', '👩🏼‍🦰'],
      ['Enric', '👨🏾'],
      ['Fina', '👩🏾‍🦱'],
      ['Guillem', '👨🏻‍🦱'],
      ['Helena', '👩🏼‍🦳'],
    ]),
    items: makeItems([
      ['guants', '🧤'],
      ['botes', '🥾'],
      ['gorra', '🧢'],
      ['etiqueta', '🏷️'],
      ['llibreta', '📗'],
      ['cordill', '🧵'],
      ['pinça', '📎'],
      ['cantimplora', '🧴'],
    ]),
    roomObjects: roomObjectCatalog.garden,
    roomObjectsByPlace: gardenRoomObjectsByPlace,
    terrainFeature: { kind: 'pond', placeIndex: clusteredObstacleRoomIndex },
    victories: ['El jardí ja està ben organitzat!'],
  },
  {
    id: 'weekend-market',
    audience: 'adults',
    title: 'El mercat de dissabte',
    introductions: ['El mercat obre amb parades, receptes i aromes.'],
    objectives: ['Organitza les persones a cada parada.'],
    places: [
      'La parada de pa',
      'La parada de fruita',
      'La parada de flors',
      'La parada de cafè',
      'La parada de ceràmica',
      'La parada de formatges',
      'La taula central',
      'L’entrada',
    ],
    characters: makePeople([
      ['Ariadna', '👩🏻'],
      ['Biel', '👨🏽'],
      ['Clara', '👩🏾'],
      ['Dani', '👨🏻'],
      ['Estel', '👩🏼‍🦰'],
      ['Fèlix', '👨🏾‍🦱'],
      ['Gina', '👩🏽‍🦱'],
      ['Hugo', '👨🏼'],
    ]),
    items: makeItems([
      ['llista', '🗒️'],
      ['moneder', '👛'],
      ['targeta', '💳'],
      ['paraigua', '🌂'],
      ['ulleres', '👓'],
      ['mocador', '🧣'],
      ['mòbil', '📱'],
      ['clauer', '🔑'],
    ]),
    roomObjects: roomObjectCatalog.market,
    roomObjectsByPlace: marketRoomObjectsByPlace,
    victories: ['El mercat ja funciona amb ordre!'],
  },
] as readonly Theme[]

export const themesForAudience = (audience: Audience) =>
  themes.filter((theme) => (theme.audience ?? 'children') === audience)

export const getTheme = (id: ThemeId) => {
  const theme = themes.find((candidate) => candidate.id === id)
  if (!theme) throw new Error(`Tema desconegut: ${id}`)
  return theme
}
