import { themes } from './themes'
import type { Locale, ThemeId } from './types'

type LabelTranslation = Readonly<Record<Locale, string>>

const label = (
  ca: string,
  es: string,
  en: string,
  eu: string,
  gl: string,
  fr: string,
  de: string,
): readonly [string, LabelTranslation] => [ca, { ca, es, en, eu, gl, fr, de }]

// cspell:disable
const translations: ReadonlyMap<string, LabelTranslation> = new Map<string, LabelTranslation>([
  label(
    'La clariana',
    'El claro',
    'The clearing',
    'Basoko soilgunea',
    'O claro',
    'La clairière',
    'Die Lichtung',
  ),
  label(
    'L’arbre gran',
    'El árbol grande',
    'The big tree',
    'Zuhaitz handia',
    'A árbore grande',
    'Le grand arbre',
    'Der große Baum',
  ),
  label(
    'El pont de fusta',
    'El puente de madera',
    'The wooden bridge',
    'Egurrezko zubia',
    'A ponte de madeira',
    'Le pont en bois',
    'Die Holzbrücke',
  ),
  label(
    'El jardí de flors',
    'El jardín de flores',
    'The flower garden',
    'Lore-lorategia',
    'O xardín de flores',
    'Le jardin fleuri',
    'Der Blumengarten',
  ),
  label('La cabana', 'La cabaña', 'The cabin', 'Txabola', 'A cabana', 'La cabane', 'Die Hütte'),
  label(
    'El rierol',
    'El arroyo',
    'The stream',
    'Erreka',
    'O regato',
    'Le ruisseau',
    'Der Bach',
  ),
  label(
    'La roca rodona',
    'La roca redonda',
    'The round rock',
    'Harri biribila',
    'A rocha redonda',
    'Le rocher rond',
    'Der runde Felsen',
  ),
  label(
    'La praderia',
    'La pradera',
    'The meadow',
    'Belardia',
    'A pradaría',
    'La prairie',
    'Die Wiese',
  ),
  label('galeta', 'galleta', 'cookie', 'gaileta', 'galleta', 'biscuit', 'Keks'),
  label('flor', 'flor', 'flower', 'lore', 'flor', 'fleur', 'Blume'),
  label('globus', 'globo', 'balloon', 'puxika', 'globo', 'ballon', 'Luftballon'),
  label('barret', 'sombrero', 'hat', 'txano', 'sombreiro', 'chapeau', 'Hut'),
  label('poma', 'manzana', 'apple', 'sagar', 'mazá', 'pomme', 'Apfel'),
  label('llibre', 'libro', 'book', 'liburu', 'libro', 'livre', 'Buch'),
  label('estrella', 'estrella', 'star', 'izar', 'estrela', 'étoile', 'Stern'),
  label('fulla', 'hoja', 'leaf', 'hosto', 'folla', 'feuille', 'Blatt'),

  label(
    'La platja suau',
    'La playa tranquila',
    'The calm beach',
    'Hondartza lasaia',
    'A praia tranquila',
    'La plage tranquille',
    'Der ruhige Strand',
  ),
  label(
    'La palmera',
    'La palmera',
    'The palm tree',
    'Palmondoa',
    'A palmeira',
    'Le palmier',
    'Die Palme',
  ),
  label(
    'La cova de petxines',
    'La cueva de conchas',
    'The seashell cave',
    'Maskorren kobazuloa',
    'A cova das cunchas',
    'La grotte aux coquillages',
    'Die Muschelhöhle',
  ),
  label(
    'El far',
    'El faro',
    'The lighthouse',
    'Itsasargia',
    'O faro',
    'Le phare',
    'Der Leuchtturm',
  ),
  label('El moll', 'El muelle', 'The pier', 'Kaia', 'O peirao', 'La jetée', 'Der Steg'),
  label(
    'La duna daurada',
    'La duna dorada',
    'The golden dune',
    'Urrezko duna',
    'A duna dourada',
    'La dune dorée',
    'Die goldene Düne',
  ),
  label(
    'La llacuna',
    'La laguna',
    'The lagoon',
    'Aintzira',
    'A lagoa',
    'Le lagon',
    'Die Lagune',
  ),
  label(
    'El mirador',
    'El mirador',
    'The lookout',
    'Behatokia',
    'O miradoiro',
    'Le belvédère',
    'Der Aussichtspunkt',
  ),
  label('petxina', 'concha', 'seashell', 'maskor', 'cuncha', 'coquillage', 'Muschel'),
  label('mapa', 'mapa', 'map', 'mapa', 'mapa', 'carte', 'Karte'),
  label('pinya', 'piña', 'pineapple', 'anana', 'ananás', 'ananas', 'Ananas'),
  label('banderí', 'banderín', 'pennant', 'banderatxo', 'bandeirola', 'fanion', 'Wimpel'),
  label('sol', 'sol', 'sun', 'eguzki', 'sol', 'soleil', 'Sonne'),
  label('cubell', 'cubo', 'bucket', 'balde', 'caldeiro', 'seau', 'Eimer'),
  label('corall', 'coral', 'coral', 'koral', 'coral', 'corail', 'Koralle'),
  label(
    'barqueta',
    'bote pequeño',
    'little boat',
    'txalupa txiki',
    'barquiña',
    'petit bateau',
    'kleines Boot',
  ),

  label(
    'La biblioteca',
    'La biblioteca',
    'The library',
    'Liburutegia',
    'A biblioteca',
    'La bibliothèque',
    'Die Bibliothek',
  ),
  label(
    'L’aula d’estrelles',
    'El aula de estrellas',
    'The star classroom',
    'Izarren ikasgela',
    'A aula das estrelas',
    'La classe des étoiles',
    'Das Sternenklassenzimmer',
  ),
  label('El pati', 'El patio', 'The courtyard', 'Patioa', 'O patio', 'La cour', 'Der Hof'),
  label('La torre', 'La torre', 'The tower', 'Dorrea', 'A torre', 'La tour', 'Der Turm'),
  label(
    'El taller',
    'El taller',
    'The workshop',
    'Tailerra',
    'O obradoiro',
    'L’atelier',
    'Die Werkstatt',
  ),
  label(
    'L’hivernacle',
    'El invernadero',
    'The greenhouse',
    'Negutegia',
    'O invernadoiro',
    'La serre',
    'Das Gewächshaus',
  ),
  label(
    'La sala de música',
    'La sala de música',
    'The music room',
    'Musika-gela',
    'A sala de música',
    'La salle de musique',
    'Der Musikraum',
  ),
  label(
    'El passadís arc de Sant Martí',
    'El pasillo arcoíris',
    'The rainbow hallway',
    'Ortzadar-pasabidea',
    'O corredor do arco da vella',
    'Le couloir arc-en-ciel',
    'Der Regenbogenflur',
  ),
  label(
    'vareta de flors',
    'varita de flores',
    'flower wand',
    'lore-makilatxo',
    'variña de flores',
    'baguette fleurie',
    'Blumenstab',
  ),
  label(
    'poció de bombolles',
    'poción de burbujas',
    'bubble potion',
    'burbuila-edabe',
    'poción de burbullas',
    'potion à bulles',
    'Seifenblasentrank',
  ),
  label(
    'llibre de contes',
    'libro de cuentos',
    'storybook',
    'ipuin-liburu',
    'libro de contos',
    'livre de contes',
    'Geschichtenbuch',
  ),
  label('capa', 'capa', 'cape', 'kapa', 'capa', 'cape', 'Umhang'),
  label(
    'clau daurada',
    'llave dorada',
    'golden key',
    'urrezko giltza',
    'chave dourada',
    'clé dorée',
    'goldener Schlüssel',
  ),
  label('ploma', 'pluma', 'feather', 'luma', 'pluma', 'plume', 'Feder'),
  label('cristall', 'cristal', 'crystal', 'kristal', 'cristal', 'cristal', 'Kristall'),

  label(
    'El planeta blau',
    'El planeta azul',
    'The blue planet',
    'Planeta urdina',
    'O planeta azul',
    'La planète bleue',
    'Der blaue Planet',
  ),
  label(
    'L’estació musical',
    'La estación musical',
    'The music station',
    'Musika-estazioa',
    'A estación musical',
    'La station musicale',
    'Die Musikstation',
  ),
  label(
    'La lluna petita',
    'La luna pequeña',
    'The small moon',
    'Ilargi txikia',
    'A lúa pequena',
    'La petite lune',
    'Der kleine Mond',
  ),
  label(
    'El jardí estel·lar',
    'El jardín estelar',
    'The star garden',
    'Izar-lorategia',
    'O xardín estelar',
    'Le jardin étoilé',
    'Der Sternengarten',
  ),
  label('El coet', 'El cohete', 'The rocket', 'Suziria', 'O foguete', 'La fusée', 'Die Rakete'),
  label(
    'L’observatori',
    'El observatorio',
    'The observatory',
    'Behatokia',
    'O observatorio',
    'L’observatoire',
    'Die Sternwarte',
  ),
  label(
    'El núvol còsmic',
    'La nube cósmica',
    'The cosmic cloud',
    'Hodei kosmikoa',
    'A nube cósmica',
    'Le nuage cosmique',
    'Die kosmische Wolke',
  ),
  label(
    'L’anella brillant',
    'El anillo brillante',
    'The bright ring',
    'Eraztun distiratsua',
    'O anel brillante',
    'L’anneau brillant',
    'Der leuchtende Ring',
  ),
  label(
    'coet petit',
    'cohete pequeño',
    'small rocket',
    'suziri txiki',
    'foguete pequeno',
    'petite fusée',
    'kleine Rakete',
  ),
  label('planeta', 'planeta', 'planet', 'planeta', 'planeta', 'planète', 'Planet'),
  label('satèl·lit', 'satélite', 'satellite', 'satelite', 'satélite', 'satellite', 'Satellit'),
  label(
    'flor lunar',
    'flor lunar',
    'moon flower',
    'ilargi-lore',
    'flor lunar',
    'fleur lunaire',
    'Mondblume',
  ),
  label(
    'comandament',
    'mando',
    'controller',
    'aginte',
    'mando',
    'boîtier de commande',
    'Steuergerät',
  ),
  label('cometa', 'cometa', 'comet', 'kometa', 'cometa', 'comète', 'Komet'),
  label(
    'auriculars',
    'auriculares',
    'headphones',
    'entzungailu',
    'auriculares',
    'casque audio',
    'Kopfhörer',
  ),

  label(
    'L’hort',
    'El huerto',
    'The vegetable garden',
    'Baratzea',
    'A horta',
    'Le potager',
    'Der Gemüsegarten',
  ),
  label(
    'El paller',
    'El pajar',
    'The hayloft',
    'Lastategia',
    'O palleiro',
    'Le grenier à foin',
    'Der Heuboden',
  ),
  label(
    'L’estable',
    'El establo',
    'The stable',
    'Ukuilua',
    'O establo',
    'L’écurie',
    'Der Stall',
  ),
  label(
    'El pomer',
    'El manzano',
    'The apple tree',
    'Sagarrondoa',
    'A maceira',
    'Le pommier',
    'Der Apfelbaum',
  ),
  label('La bassa', 'El estanque', 'The pond', 'Urmaela', 'A poza', 'L’étang', 'Der Teich'),
  label('El molí', 'El molino', 'The mill', 'Errota', 'O muíño', 'Le moulin', 'Die Mühle'),
  label(
    'La tanca blava',
    'La valla azul',
    'The blue fence',
    'Hesi urdina',
    'O valado azul',
    'La clôture bleue',
    'Der blaue Zaun',
  ),
  label(
    'La caseta',
    'La casita',
    'The little shed',
    'Etxolatxoa',
    'A casiña',
    'Le petit abri',
    'Der kleine Schuppen',
  ),
  label('pastanaga', 'zanahoria', 'carrot', 'azenario', 'cenoria', 'carotte', 'Karotte'),
  label('blat', 'trigo', 'wheat', 'gari', 'trigo', 'blé', 'Weizen'),
  label('llet', 'leche', 'milk', 'esne', 'leite', 'lait', 'Milch'),
  label(
    'regadora',
    'regadera',
    'watering can',
    'ureztagailu',
    'regadeira',
    'arrosoir',
    'Gießkanne',
  ),
  label('cistell', 'cesto', 'basket', 'saski', 'cesta', 'panier', 'Korb'),
  label(
    'campaneta',
    'campanilla',
    'small bell',
    'kanpaitxo',
    'campaíña',
    'clochette',
    'Glöckchen',
  ),

  label(
    'El corall rosa',
    'El coral rosa',
    'The pink coral',
    'Koral arrosa',
    'O coral rosa',
    'Le corail rose',
    'Die rosa Koralle',
  ),
  label(
    'La cova blava',
    'La cueva azul',
    'The blue cave',
    'Haitzulo urdina',
    'A cova azul',
    'La grotte bleue',
    'Die blaue Höhle',
  ),
  label(
    'L’alguer',
    'El campo de algas',
    'The seaweed bed',
    'Alga-belardia',
    'A pradería de algas',
    'L’herbier d’algues',
    'Die Seegraswiese',
  ),
  label(
    'La petxina gran',
    'La concha grande',
    'The big seashell',
    'Maskor handia',
    'A cuncha grande',
    'Le grand coquillage',
    'Die große Muschel',
  ),
  label(
    'La roca cantant',
    'La roca cantora',
    'The singing rock',
    'Harri kantaria',
    'A rocha cantora',
    'Le rocher chantant',
    'Der singende Felsen',
  ),
  label(
    'El jardí de perles',
    'El jardín de perlas',
    'The pearl garden',
    'Perla-lorategia',
    'O xardín de perlas',
    'Le jardin de perles',
    'Der Perlengarten',
  ),
  label(
    'La bombolla gegant',
    'La burbuja gigante',
    'The giant bubble',
    'Burbuila erraldoia',
    'A burbulla xigante',
    'La bulle géante',
    'Die Riesenblase',
  ),
  label(
    'El sorral',
    'El arenal',
    'The sandy patch',
    'Hareatza',
    'O areal',
    'Le coin de sable',
    'Die Sandfläche',
  ),
  label('perla', 'perla', 'pearl', 'perla', 'perla', 'perle', 'Perle'),
  label('alga', 'alga', 'seaweed', 'alga', 'alga', 'algue', 'Alge'),
  label(
    'estrella marina',
    'estrella de mar',
    'starfish',
    'itsas izar',
    'estrela de mar',
    'étoile de mer',
    'Seestern',
  ),
  label(
    'peixet',
    'pez pequeño',
    'little fish',
    'arrain txiki',
    'peixiño',
    'petit poisson',
    'kleiner Fisch',
  ),
  label('bombolla', 'burbuja', 'bubble', 'burbuila', 'burbulla', 'bulle', 'Blase'),
  label('corona', 'corona', 'crown', 'koroa', 'coroa', 'couronne', 'Krone'),

  label(
    'El niu de fulles',
    'El nido de hojas',
    'The leaf nest',
    'Hosto-habia',
    'O niño de follas',
    'Le nid de feuilles',
    'Das Blätternest',
  ),
  label('El llac', 'El lago', 'The lake', 'Aintzira', 'O lago', 'Le lac', 'Der See'),
  label(
    'La roca alta',
    'La roca alta',
    'The tall rock',
    'Harri garaia',
    'A rocha alta',
    'Le haut rocher',
    'Der hohe Felsen',
  ),
  label(
    'El bosc de falgueres',
    'El bosque de helechos',
    'The fern forest',
    'Iratze-basoa',
    'O bosque de fentos',
    'La forêt de fougères',
    'Der Farnwald',
  ),
  label('La vall', 'El valle', 'The valley', 'Harana', 'O val', 'La vallée', 'Das Tal'),
  label('El pont', 'El puente', 'The bridge', 'Zubia', 'A ponte', 'Le pont', 'Die Brücke'),
  label(
    'La font',
    'La fuente',
    'The fountain',
    'Iturria',
    'A fonte',
    'La fontaine',
    'Der Brunnen',
  ),
  label('El turó', 'La colina', 'The hill', 'Muinoa', 'O outeiro', 'La colline', 'Der Hügel'),
  label('petjada', 'huella', 'footprint', 'oinatz', 'pegada', 'empreinte', 'Fußabdruck'),
  label('motxilla', 'mochila', 'backpack', 'motxila', 'mochila', 'sac à dos', 'Rucksack'),
  label(
    'prismàtics',
    'prismáticos',
    'binoculars',
    'prismatiko',
    'prismáticos',
    'jumelles',
    'Fernglas',
  ),
  label(
    'pedreta',
    'piedra pequeña',
    'pebble',
    'harri-koskor',
    'pedriña',
    'caillou',
    'Kieselstein',
  ),

  label(
    'La plaça',
    'La plaza',
    'The town square',
    'Plaza',
    'A praza',
    'La place',
    'Der Marktplatz',
  ),
  label(
    'La fleca',
    'La panadería',
    'The bakery',
    'Okindegia',
    'A panadaría',
    'La boulangerie',
    'Die Bäckerei',
  ),
  label('El cinema', 'El cine', 'The cinema', 'Zinema', 'O cine', 'Le cinéma', 'Das Kino'),
  label(
    'El jardí',
    'El jardín',
    'The garden',
    'Lorategia',
    'O xardín',
    'Le jardin',
    'Der Garten',
  ),
  label(
    'La caseta groga',
    'La casita amarilla',
    'The little yellow house',
    'Etxetxo horia',
    'A casiña amarela',
    'La petite maison jaune',
    'Das kleine gelbe Haus',
  ),
  label('pastís', 'pastel', 'cake', 'tarta', 'pastel', 'gâteau', 'Kuchen'),
  label('pintura', 'pintura', 'paint', 'pintura', 'pintura', 'peinture', 'Farbe'),
  label('música', 'música', 'music', 'musika', 'música', 'musique', 'Musik'),

  label(
    'La roda de colors',
    'La rueda de colores',
    'The color wheel',
    'Kolore-gurpila',
    'A roda de cores',
    'La roue des couleurs',
    'Das Farbenrad',
  ),
  label(
    'La parada groga',
    'El puesto amarillo',
    'The yellow stall',
    'Postu horia',
    'O posto amarelo',
    'Le stand jaune',
    'Der gelbe Stand',
  ),
  label(
    'El teatre',
    'El teatro',
    'The theater',
    'Antzokia',
    'O teatro',
    'Le théâtre',
    'Das Theater',
  ),
  label(
    'El jardí de globus',
    'El jardín de globos',
    'The balloon garden',
    'Puxiken lorategia',
    'O xardín de globos',
    'Le jardin de ballons',
    'Der Luftballongarten',
  ),
  label(
    'La carpa',
    'La carpa',
    'The big top',
    'Zirku-karpa',
    'A carpa do circo',
    'Le chapiteau',
    'Das Zirkuszelt',
  ),
  label(
    'El carrusel',
    'El carrusel',
    'The carousel',
    'Karrusela',
    'O carrusel',
    'Le carrousel',
    'Das Karussell',
  ),
  label(
    'El racó de contes',
    'El rincón de cuentos',
    'The story corner',
    'Ipuinen txokoa',
    'O recuncho dos contos',
    'Le coin des histoires',
    'Die Geschichtenecke',
  ),
  label(
    'La fonteta',
    'La fuente pequeña',
    'The small fountain',
    'Iturritxoa',
    'A fonte pequena',
    'La petite fontaine',
    'Der kleine Brunnen',
  ),
  label('entrada', 'entrada', 'ticket', 'sarrera', 'entrada', 'billet', 'Eintrittskarte'),
  label('pinzell', 'pincel', 'paintbrush', 'pintzel', 'pincel', 'pinceau', 'Pinsel'),
  label('cor', 'corazón', 'heart', 'bihotz', 'corazón', 'cœur', 'Herz'),
  label('cinta', 'cinta', 'ribbon', 'zinta', 'cinta', 'ruban', 'Band'),
  label('conte', 'cuento', 'story', 'ipuin', 'conto', 'histoire', 'Geschichte'),

  label(
    'El refugi',
    'El refugio',
    'The shelter',
    'Aterpea',
    'O refuxio',
    'Le refuge',
    'Die Berghütte',
  ),
  label('El prat', 'El prado', 'The meadow', 'Belardia', 'O prado', 'Le pré', 'Die Wiese'),
  label(
    'La cascada suau',
    'La cascada tranquila',
    'The gentle waterfall',
    'Ur-jauzi lasaia',
    'A fervenza tranquila',
    'La cascade paisible',
    'Der sanfte Wasserfall',
  ),
  label('El bosc', 'El bosque', 'The forest', 'Basoa', 'O bosque', 'La forêt', 'Der Wald'),
  label(
    'El pontet',
    'El puente pequeño',
    'The small bridge',
    'Zubitxoa',
    'A ponte pequena',
    'Le petit pont',
    'Die kleine Brücke',
  ),
  label(
    'La cova de colors',
    'La cueva de colores',
    'The colorful cave',
    'Koloretako kobazuloa',
    'A cova de cores',
    'La grotte colorée',
    'Die bunte Höhle',
  ),
  label('El cim', 'La cima', 'The summit', 'Gailurra', 'O cumio', 'Le sommet', 'Der Gipfel'),
  label(
    'cantimplora',
    'cantimplora',
    'water bottle',
    'kantinplora',
    'cantimplora',
    'gourde',
    'Trinkflasche',
  ),

  label(
    'La cabina 1',
    'La cabina 1',
    'Booth 1',
    '1. kabina',
    'A cabina 1',
    'La cabine 1',
    'Kabine 1',
  ),
  label(
    'La cabina 2',
    'La cabina 2',
    'Booth 2',
    '2. kabina',
    'A cabina 2',
    'La cabine 2',
    'Kabine 2',
  ),
  label(
    'La taula de mescles',
    'La mesa de mezclas',
    'The mixing desk',
    'Nahasketa-mahaia',
    'A mesa de mesturas',
    'La console de mixage',
    'Das Mischpult',
  ),
  label(
    'El teclat',
    'El teclado',
    'The keyboard',
    'Teklatua',
    'O teclado',
    'Le clavier',
    'Das Keyboard',
  ),
  label(
    'El mural de pòsters',
    'El mural de pósteres',
    'The poster wall',
    'Kartelen horma',
    'O mural de carteis',
    'Le mur d’affiches',
    'Die Posterwand',
  ),
  label(
    'La sala d’assaig',
    'La sala de ensayo',
    'The rehearsal room',
    'Entsegu-gela',
    'A sala de ensaio',
    'La salle de répétition',
    'Der Proberaum',
  ),
  label(
    'El racó del baix',
    'El rincón del bajo',
    'The bass corner',
    'Baxuaren txokoa',
    'O recuncho do baixo',
    'Le coin de la basse',
    'Die Bass-Ecke',
  ),
  label(
    'El sofà blau',
    'El sofá azul',
    'The blue sofa',
    'Sofa urdina',
    'O sofá azul',
    'Le canapé bleu',
    'Das blaue Sofa',
  ),
  label(
    'acreditació',
    'acreditación',
    'pass',
    'akreditazio',
    'acreditación',
    'badge',
    'Ausweis',
  ),
  label('mòbil', 'móvil', 'phone', 'mugikor', 'móbil', 'téléphone', 'Handy'),
  label('gorra', 'gorra', 'cap', 'txano', 'gorra', 'casquette', 'Kappe'),
  label('jaqueta', 'chaqueta', 'jacket', 'jaka', 'chaqueta', 'veste', 'Jacke'),
  label('ulleres', 'gafas', 'glasses', 'betaurrekoak', 'lentes', 'lunettes', 'Brille'),
  label('rellotge', 'reloj', 'watch', 'eskumuturreko erloju', 'reloxo', 'montre', 'Armbanduhr'),
  label('carpeta', 'carpeta', 'folder', 'karpeta', 'cartafol', 'dossier', 'Mappe'),
  label(
    'micròfon de peu',
    'micrófono de pie',
    'stand microphone',
    'zutikako mikrofono',
    'micrófono de pé',
    'micro sur pied',
    'Standmikrofon',
  ),
  label('mesclador', 'mezclador', 'mixer', 'nahasgailu', 'mesturador', 'mixeur audio', 'Mixer'),
  label(
    'taula de control',
    'mesa de control',
    'control desk',
    'kontrol-mahai',
    'mesa de control',
    'console de contrôle',
    'Regiepult',
  ),
  label(
    'altaveu',
    'altavoz',
    'speaker',
    'bozgorailu',
    'altofalante',
    'enceinte',
    'Lautsprecher',
  ),
  label('teclat', 'teclado', 'keyboard', 'teklatu', 'teclado', 'clavier', 'Keyboard'),
  label('tambor', 'tambor', 'drum', 'danbor', 'tambor', 'tambour', 'Trommel'),
  label('guitarra', 'guitarra', 'guitar', 'gitarra', 'guitarra', 'guitare', 'Gitarre'),
  label('saxòfon', 'saxofón', 'saxophone', 'saxofoi', 'saxofón', 'saxophone', 'Saxofon'),
  label('violí', 'violín', 'violin', 'biolin', 'violín', 'violon', 'Geige'),
  label('cadira', 'silla', 'chair', 'aulki', 'cadeira', 'chaise', 'Stuhl'),
  label(
    'llum de taula',
    'lámpara de mesa',
    'table lamp',
    'mahai-lanpara',
    'lámpada de mesa',
    'lampe de table',
    'Tischlampe',
  ),
  label('armari', 'armario', 'cabinet', 'armairu', 'armario', 'armoire', 'Schrank'),
  label(
    'caixa d’eines',
    'caja de herramientas',
    'toolbox',
    'tresna-kutxa',
    'caixa de ferramentas',
    'boîte à outils',
    'Werkzeugkasten',
  ),
  label(
    'bloc de notes',
    'bloc de notas',
    'notepad',
    'ohar-blok',
    'bloco de notas',
    'bloc-notes',
    'Notizblock',
  ),
  label(
    'partitura',
    'partitura',
    'sheet music',
    'partitura',
    'partitura',
    'partition',
    'Notenblatt',
  ),
  label(
    'ordinador',
    'ordenador',
    'computer',
    'ordenagailu',
    'ordenador',
    'ordinateur',
    'Computer',
  ),
  label(
    'temporitzador',
    'temporizador',
    'timer',
    'tenporizadore',
    'temporizador',
    'minuteur',
    'Timer',
  ),
  label(
    'endoll',
    'enchufe',
    'power socket',
    'entxufe',
    'toma de corrente',
    'prise électrique',
    'Steckdose',
  ),
  label(
    'got d’aigua',
    'vaso de agua',
    'glass of water',
    'ur-baso',
    'vaso de auga',
    'verre d’eau',
    'Glas Wasser',
  ),

  label(
    'La pista verda',
    'La pista verde',
    'The green court',
    'Kantxa berdea',
    'A pista verde',
    'Le terrain vert',
    'Das grüne Spielfeld',
  ),
  label(
    'La pista blava',
    'La pista azul',
    'The blue court',
    'Kantxa urdina',
    'A pista azul',
    'Le terrain bleu',
    'Das blaue Spielfeld',
  ),
  label(
    'El mur d’escalada',
    'El muro de escalada',
    'The climbing wall',
    'Eskalada-horma',
    'O muro de escalada',
    'Le mur d’escalade',
    'Die Kletterwand',
  ),
  label(
    'La zona d’estiraments',
    'La zona de estiramientos',
    'The stretching area',
    'Luzatze-gunea',
    'A zona de estiramentos',
    'La zone d’étirements',
    'Der Dehnbereich',
  ),
  label(
    'La taula de marques',
    'La mesa de marcas',
    'The score table',
    'Markagailu-mahaia',
    'A mesa de puntuacións',
    'La table de marque',
    'Der Wertungstisch',
  ),
  label(
    'El circuit',
    'El circuito',
    'The course',
    'Ibilbidea',
    'O circuíto',
    'Le parcours',
    'Der Parcours',
  ),
  label(
    'La grada',
    'La grada',
    'The bleachers',
    'Harmaila',
    'A bancada',
    'Les gradins',
    'Die Tribüne',
  ),
  label(
    'El punt d’aigua',
    'El punto de agua',
    'The water point',
    'Ur-gunea',
    'O punto de auga',
    'Le point d’eau',
    'Die Wasserstation',
  ),
  label('dorsal', 'dorsal', 'bib', 'dortsal', 'dorsal', 'dossard', 'Startnummer'),
  label('casc', 'casco', 'helmet', 'kasko', 'casco', 'casque', 'Helm'),
  label('mocador', 'pañuelo', 'scarf', 'zapi', 'bufanda', 'écharpe', 'Schal'),
  label(
    'sabatilles',
    'zapatillas',
    'trainers',
    'kirol-oinetakoak',
    'zapatillas de deporte',
    'baskets',
    'Turnschuhe',
  ),
  label(
    'pilota de bàsquet',
    'balón de baloncesto',
    'basketball',
    'saskibaloiko baloi',
    'balón de baloncesto',
    'ballon de basket',
    'Basketball',
  ),
  label(
    'pilota de futbol',
    'balón de fútbol',
    'football',
    'futbol-baloi',
    'balón de fútbol',
    'ballon de football',
    'Fußball',
  ),
  label(
    'pilota de voleibol',
    'balón de voleibol',
    'volleyball',
    'boleibol-baloi',
    'balón de voleibol',
    'ballon de volley',
    'Volleyball',
  ),
  label(
    'disc',
    'disco volador',
    'flying disc',
    'disko hegalari',
    'disco voador',
    'disque volant',
    'Frisbee',
  ),
  label(
    'raqueta de taula',
    'pala de tenis de mesa',
    'table tennis paddle',
    'mahai-teniseko pala',
    'pa de tenis de mesa',
    'raquette de tennis de table',
    'Tischtennisschläger',
  ),
  label('porteria', 'portería', 'goal', 'ate', 'portería', 'but', 'Tor'),
  label(
    'patí',
    'monopatín',
    'skateboard',
    'monopatin',
    'monopatín',
    'planche à roulettes',
    'Skateboard',
  ),
  label('bicicleta', 'bicicleta', 'bicycle', 'bizikleta', 'bicicleta', 'vélo', 'Fahrrad'),
  label('banc', 'banco', 'bench', 'banku', 'banco', 'banc', 'Bank'),
  label(
    'font d’aigua',
    'fuente de agua',
    'water fountain',
    'edateko iturri',
    'fonte para beber',
    'fontaine à eau',
    'Trinkbrunnen',
  ),
  label(
    'cronòmetre',
    'cronómetro',
    'stopwatch',
    'kronometro',
    'cronómetro',
    'chronomètre',
    'Stoppuhr',
  ),
  label('megàfon', 'megáfono', 'megaphone', 'megafono', 'megáfono', 'mégaphone', 'Megafon'),
  label(
    'samarreta',
    'camiseta',
    'shirt',
    'kirol-kamiseta',
    'camiseta',
    'maillot',
    'Sportshirt',
  ),
  label('cistella', 'cesta', 'basket', 'saski', 'cesta', 'panier', 'Korb'),
  label('ampolla', 'botella', 'bottle', 'botila', 'botella', 'bouteille', 'Flasche'),
  label(
    'bossa d’equip',
    'bolsa de equipo',
    'kit bag',
    'kirol-poltsa',
    'bolsa de equipo',
    'sac de sport',
    'Sporttasche',
  ),
  label('escala', 'escalera', 'ladder', 'eskailera', 'escaleira', 'échelle', 'Leiter'),
  label('trofeu', 'trofeo', 'trophy', 'garaikur', 'trofeo', 'trophée', 'Pokal'),
  label('medalla', 'medalla', 'medal', 'domina', 'medalla', 'médaille', 'Medaille'),

  label(
    'La taula de disseny',
    'La mesa de diseño',
    'The design table',
    'Diseinu-mahaia',
    'A mesa de deseño',
    'La table de conception',
    'Der Designtisch',
  ),
  label(
    'La paret d’idees',
    'La pared de ideas',
    'The ideas wall',
    'Ideien horma',
    'A parede das ideas',
    'Le mur des idées',
    'Die Ideenwand',
  ),
  label(
    'L’estació de color',
    'La estación de color',
    'The color station',
    'Kolore-estazioa',
    'A estación da cor',
    'Le poste de mise en couleur',
    'Die Farbstation',
  ),
  label(
    'El racó de vídeo',
    'El rincón de vídeo',
    'The video corner',
    'Bideo-txokoa',
    'O recuncho de vídeo',
    'Le coin vidéo',
    'Die Videoecke',
  ),
  label(
    'La impressora',
    'La impresora',
    'The printer',
    'Inprimagailua',
    'A impresora',
    'L’imprimante',
    'Der Drucker',
  ),
  label(
    'La taula de maquetes',
    'La mesa de maquetas',
    'The model table',
    'Maketen mahaia',
    'A mesa de maquetas',
    'La table des maquettes',
    'Der Modelltisch',
  ),
  label(
    'El sofà de prova',
    'El sofá de prueba',
    'The testing sofa',
    'Proba-sofa',
    'O sofá de probas',
    'Le canapé d’essai',
    'Das Testsofa',
  ),
  label(
    'La finestra gran',
    'La ventana grande',
    'The large window',
    'Leiho handia',
    'A fiestra grande',
    'La grande fenêtre',
    'Das große Fenster',
  ),
  label('llapis', 'lápiz', 'pencil', 'arkatz', 'lapis', 'crayon', 'Bleistift'),
  label('goma', 'goma', 'eraser', 'borragoma', 'goma de borrar', 'gomme', 'Radiergummi'),
  label(
    'portafolis',
    'portafolios',
    'portfolio',
    'portfolio',
    'portafolios',
    'portfolio',
    'Portfolio',
  ),
  label('retolador', 'rotulador', 'marker', 'errotuladore', 'rotulador', 'feutre', 'Filzstift'),
  label('pantalla', 'pantalla', 'screen', 'pantaila', 'pantalla', 'écran', 'Bildschirm'),
  label(
    'impressora',
    'impresora',
    'printer',
    'inprimagailu',
    'impresora',
    'imprimante',
    'Drucker',
  ),
  label('càmera', 'cámara', 'camera', 'kamera', 'cámara', 'appareil photo', 'Kamera'),
  label(
    'llum de treball',
    'lámpara de trabajo',
    'work lamp',
    'laneko lanpara',
    'lámpada de traballo',
    'lampe de travail',
    'Arbeitslampe',
  ),
  label('escaire', 'escuadra', 'set square', 'eskuaira', 'escuadra', 'équerre', 'Geodreieck'),
  label('regle', 'regla', 'ruler', 'erregela', 'regra', 'règle', 'Lineal'),
  label(
    'paleta de color',
    'paleta de color',
    'color palette',
    'kolore-paleta',
    'paleta de cores',
    'palette de couleurs',
    'Farbpalette',
  ),
  label(
    'rodet de fil',
    'carrete de hilo',
    'thread spool',
    'hari-bobina',
    'carrete de fío',
    'bobine de fil',
    'Garnrolle',
  ),
  label(
    'cabdell',
    'ovillo',
    'ball of yarn',
    'hari-mataza',
    'nobelo',
    'pelote de laine',
    'Wollknäuel',
  ),
  label('xinxeta', 'chincheta', 'pushpin', 'txintxeta', 'chincheta', 'punaise', 'Reißzwecke'),
  label('llibres', 'libros', 'books', 'liburuak', 'libros', 'livres', 'Bücher'),
  label(
    'bloc d’esbossos',
    'bloc de bocetos',
    'sketchbook',
    'zirriborro-koaderno',
    'caderno de bosquexos',
    'carnet de croquis',
    'Skizzenbuch',
  ),
  label('marc', 'marco', 'frame', 'marko', 'marco', 'cadre', 'Rahmen'),
  label('maqueta', 'maqueta', 'model', 'maketa', 'maqueta', 'maquette', 'Modell'),
  label(
    'portàtil',
    'portátil',
    'laptop',
    'ordenagailu eramangarri',
    'portátil',
    'ordinateur portable',
    'Laptop',
  ),
  label('mirall', 'espejo', 'mirror', 'ispilu', 'espello', 'miroir', 'Spiegel'),
  label('caixa', 'caja', 'box', 'kutxa', 'caixa', 'boîte', 'Kiste'),

  label(
    'La taula rodona',
    'La mesa redonda',
    'The round table',
    'Mahai biribila',
    'A mesa redonda',
    'La table ronde',
    'Der runde Tisch',
  ),
  label(
    'La butaca verda',
    'El sillón verde',
    'The green armchair',
    'Besaulki berdea',
    'A butaca verde',
    'Le fauteuil vert',
    'Der grüne Sessel',
  ),
  label(
    'El finestral',
    'El ventanal',
    'The picture window',
    'Leihate handia',
    'O ventanal',
    'La baie vitrée',
    'Das Panoramafenster',
  ),
  label(
    'La prestatgeria',
    'La estantería',
    'The bookshelf',
    'Liburu-apalategia',
    'A estantería',
    'L’étagère à livres',
    'Das Bücherregal',
  ),
  label(
    'La taula petita',
    'La mesa pequeña',
    'The small table',
    'Mahai txikia',
    'A mesa pequena',
    'La petite table',
    'Der kleine Tisch',
  ),
  label(
    'El racó tranquil',
    'El rincón tranquilo',
    'The quiet corner',
    'Txoko lasaia',
    'O recuncho tranquilo',
    'Le coin tranquille',
    'Die ruhige Ecke',
  ),
  label(
    'La llum de peu',
    'La lámpara de pie',
    'The floor lamp',
    'Zutikako lanpara',
    'A lámpada de pé',
    'Le lampadaire',
    'Die Stehlampe',
  ),
  label(
    'La cafetera',
    'La cafetera',
    'The coffee maker',
    'Kafe-makina',
    'A cafeteira',
    'La cafetière',
    'Die Kaffeemaschine',
  ),
  label('novel·la', 'novela', 'novel', 'eleberri', 'novela', 'roman', 'Roman'),
  label(
    'punt de llibre',
    'marcapáginas',
    'bookmark',
    'liburu-marka',
    'marcapáxinas',
    'marque-page',
    'Lesezeichen',
  ),
  label('quadern', 'cuaderno', 'notebook', 'koaderno', 'caderno', 'carnet', 'Notizbuch'),
  label('fullet', 'folleto', 'leaflet', 'liburuxka', 'folleto', 'dépliant', 'Faltblatt'),
  label('bossa', 'bolso', 'bag', 'poltsa', 'bolso', 'sac', 'Tasche'),
  label('sofà', 'sofá', 'sofa', 'sofa', 'sofá', 'canapé', 'Sofa'),
  label('planta', 'planta', 'plant', 'landare', 'planta', 'plante', 'Pflanze'),
  label(
    'llum de lectura',
    'lámpara de lectura',
    'reading lamp',
    'irakurtzeko lanpara',
    'lámpada de lectura',
    'lampe de lecture',
    'Leselampe',
  ),
  label('tassa', 'taza', 'mug', 'katilu', 'cunca', 'tasse', 'Becher'),
  label('tetera', 'tetera', 'teapot', 'teontzi', 'teteira', 'théière', 'Teekanne'),
  label('diari', 'periódico', 'newspaper', 'egunkari', 'xornal', 'journal', 'Zeitung'),
  label('quadre', 'cuadro', 'picture', 'koadro', 'cadro', 'tableau', 'Bild'),
  label(
    'revister',
    'revistero',
    'magazine rack',
    'aldizkari-euskarri',
    'revistero',
    'porte-revues',
    'Zeitschriftenständer',
  ),
  label(
    'llibre obert',
    'libro abierto',
    'open book',
    'liburu ireki',
    'libro aberto',
    'livre ouvert',
    'offenes Buch',
  ),
  label('finestra', 'ventana', 'window', 'leiho', 'fiestra', 'fenêtre', 'Fenster'),
  label('porta', 'puerta', 'door', 'ate', 'porta', 'porte', 'Tür'),
  label(
    'paraigüer',
    'paragüero',
    'umbrella stand',
    'aterki-ontzi',
    'paragüeiro',
    'porte-parapluies',
    'Schirmständer',
  ),

  label(
    'L’hort alt',
    'El bancal elevado',
    'The raised garden bed',
    'Baratze altxatua',
    'O bancal elevado',
    'Le bac surélevé',
    'Das Hochbeet',
  ),
  label(
    'La taula de llavors',
    'La mesa de semillas',
    'The seed table',
    'Hazien mahaia',
    'A mesa de sementes',
    'La table des graines',
    'Der Samentisch',
  ),
  label(
    'El banc llarg',
    'El banco largo',
    'The long bench',
    'Banku luzea',
    'O banco longo',
    'Le banc long',
    'Die lange Bank',
  ),
  label(
    'La pèrgola',
    'La pérgola',
    'The pergola',
    'Pergola',
    'A pérgola',
    'La pergola',
    'Die Pergola',
  ),
  label(
    'La vora de la bassa',
    'El borde del estanque',
    'The pond edge',
    'Urmaelaren ertza',
    'A beira da poza',
    'Le bord de l’étang',
    'Der Teichrand',
  ),
  label(
    'El compostador',
    'El compostador',
    'The compost bin',
    'Konpostagailua',
    'O composteiro',
    'Le composteur',
    'Der Komposter',
  ),
  label(
    'La taula d’eines',
    'La mesa de herramientas',
    'The tool table',
    'Tresnen mahaia',
    'A mesa de ferramentas',
    'La table à outils',
    'Der Werkzeugtisch',
  ),
  label(
    'La porta blava',
    'La puerta azul',
    'The blue door',
    'Ate urdina',
    'A porta azul',
    'La porte bleue',
    'Die blaue Tür',
  ),
  label('guants', 'guantes', 'gloves', 'eskularruak', 'luvas', 'gants', 'Handschuhe'),
  label('botes', 'botas', 'boots', 'botak', 'botas', 'bottes', 'Stiefel'),
  label('etiqueta', 'etiqueta', 'label', 'etiketa', 'etiqueta', 'étiquette', 'Etikett'),
  label('llibreta', 'libreta', 'notebook', 'koadernotxo', 'libreta', 'carnet', 'Notizheft'),
  label('cordill', 'cordel', 'string', 'lokarri', 'cordel', 'ficelle', 'Schnur'),
  label('pinça', 'pinza', 'clip', 'klip', 'pinza', 'pince', 'Klammer'),
  label('test', 'maceta', 'plant pot', 'loreontzi', 'maceta', 'pot de fleurs', 'Blumentopf'),
  label('galleda', 'cubo', 'bucket', 'balde', 'caldeiro', 'seau', 'Eimer'),
  label(
    'tanca baixa',
    'valla baja',
    'low fence',
    'hesi baxu',
    'valado baixo',
    'clôture basse',
    'niedriger Zaun',
  ),
  label('fusta', 'madera', 'wood', 'egur', 'madeira', 'bois', 'Holz'),
  label('pedra', 'piedra', 'stone', 'harri', 'pedra', 'pierre', 'Stein'),
  label(
    'planter',
    'bandeja de semillero',
    'seed tray',
    'hazitegi-erretilu',
    'bandexa de sementeira',
    'plateau de semis',
    'Anzuchtschale',
  ),
  label('cartell', 'cartel', 'sign', 'kartel', 'cartel', 'panneau', 'Schild'),
  label('aixeta', 'grifo', 'tap', 'txorrota', 'billa', 'robinet', 'Wasserhahn'),
  label(
    'carretó',
    'carretilla',
    'wheelbarrow',
    'eskorga',
    'carreta de man',
    'brouette',
    'Schubkarre',
  ),
  label('gira-sol', 'girasol', 'sunflower', 'ekilore', 'xirasol', 'tournesol', 'Sonnenblume'),
  label('tomàquet', 'tomate', 'tomato', 'tomate', 'tomate', 'tomate', 'Tomate'),
  label('pèsols', 'guisantes', 'peas', 'ilar', 'chícharos', 'petits pois', 'Erbsen'),
  label('maó', 'ladrillo', 'brick', 'adreilu', 'ladrillo', 'brique', 'Ziegelstein'),
  label('escombra', 'escoba', 'broom', 'erratz', 'vasoira', 'balai', 'Besen'),
  label('esponja', 'esponja', 'sponge', 'belaki', 'esponxa', 'éponge', 'Schwamm'),
  label('gerro', 'jarrón', 'vase', 'pitxer', 'floreiro', 'vase', 'Vase'),
  label('nenúfar', 'nenúfar', 'water lily', 'nenufar', 'nenúfar', 'nénuphar', 'Seerose'),
  label(
    'gota d’aigua',
    'gota de agua',
    'water drop',
    'ur-tanta',
    'gota de auga',
    'goutte d’eau',
    'Wassertropfen',
  ),
  label('granota', 'rana', 'frog', 'igel', 'ra', 'grenouille', 'Frosch'),
  label('ànec', 'pato', 'duck', 'ahate', 'pato', 'canard', 'Ente'),
  label(
    'fulles seques',
    'hojas secas',
    'dry leaves',
    'hosto lehorrak',
    'follas secas',
    'feuilles sèches',
    'trockene Blätter',
  ),
  label(
    'cuc de terra',
    'lombriz',
    'earthworm',
    'lur-zizare',
    'miñoca',
    'ver de terre',
    'Regenwurm',
  ),

  label(
    'La parada de pa',
    'El puesto de pan',
    'The bread stall',
    'Ogi-postua',
    'O posto de pan',
    'Le stand de pain',
    'Der Brotstand',
  ),
  label(
    'La parada de fruita',
    'El puesto de fruta',
    'The fruit stall',
    'Fruta-postua',
    'O posto de froita',
    'Le stand de fruits',
    'Der Obststand',
  ),
  label(
    'La parada de flors',
    'El puesto de flores',
    'The flower stall',
    'Lore-postua',
    'O posto de flores',
    'Le stand de fleurs',
    'Der Blumenstand',
  ),
  label(
    'La parada de cafè',
    'El puesto de café',
    'The coffee stall',
    'Kafe-postua',
    'O posto de café',
    'Le stand de café',
    'Der Kaffeestand',
  ),
  label(
    'La parada de ceràmica',
    'El puesto de cerámica',
    'The pottery stall',
    'Zeramika-postua',
    'O posto de cerámica',
    'Le stand de poterie',
    'Der Keramikstand',
  ),
  label(
    'La parada de formatges',
    'El puesto de quesos',
    'The cheese stall',
    'Gazta-postua',
    'O posto de queixos',
    'Le stand de fromages',
    'Der Käsestand',
  ),
  label(
    'La taula central',
    'La mesa central',
    'The central table',
    'Erdiko mahaia',
    'A mesa central',
    'La table centrale',
    'Der zentrale Tisch',
  ),
  label(
    'L’entrada',
    'La entrada',
    'The entrance',
    'Sarrera',
    'A entrada',
    'L’entrée',
    'Der Eingang',
  ),
  label('llista', 'lista', 'list', 'zerrenda', 'lista', 'liste', 'Liste'),
  label('moneder', 'monedero', 'wallet', 'diru-zorro', 'carteira', 'portefeuille', 'Geldbörse'),
  label('targeta', 'tarjeta', 'card', 'txartel', 'tarxeta', 'carte', 'Karte'),
  label('paraigua', 'paraguas', 'umbrella', 'aterki', 'paraugas', 'parapluie', 'Regenschirm'),
  label(
    'clauer',
    'llavero',
    'key ring',
    'giltzatako',
    'chaveiro',
    'porte-clés',
    'Schlüsselanhänger',
  ),
  label('balança', 'balanza', 'scales', 'balantza', 'balanza', 'balance', 'Waage'),
  label('rebut', 'recibo', 'receipt', 'ordainagiri', 'recibo', 'reçu', 'Kassenbon'),
  label('formatge', 'queso', 'cheese', 'gazta', 'queixo', 'fromage', 'Käse'),
  label('pa', 'pan', 'bread', 'ogi', 'pan', 'pain', 'Brot'),
  label('ram', 'ramo', 'bouquet', 'lore-sorta', 'ramo', 'bouquet', 'Blumenstrauß'),
  label('pot', 'tarro', 'jar', 'pote', 'tarro', 'bocal', 'Einmachglas'),
  label('pera', 'pera', 'pear', 'udare', 'pera', 'poire', 'Birne'),
])

const themeOverrides: Readonly<
  Partial<Record<ThemeId, ReadonlyMap<string, LabelTranslation>>>
> = {
  'book-club': new Map<string, LabelTranslation>([
    label(
      'ploma',
      'estilográfica',
      'fountain pen',
      'luma estilografiko',
      'pluma estilográfica',
      'stylo-plume',
      'Füllfederhalter',
    ),
    label('rellotge', 'reloj', 'clock', 'erloju', 'reloxo', 'horloge', 'Uhr'),
  ]),
  'sports-festival': new Map<string, LabelTranslation>([
    label(
      'banderí',
      'banderín de señalización',
      'marker flag',
      'seinale-banderatxo',
      'bandeirola de sinalización',
      'fanion de balisage',
      'Markierungsfahne',
    ),
  ]),
  'weekend-market': new Map<string, LabelTranslation>([
    label(
      'bossa',
      'bolsa de la compra',
      'shopping bag',
      'erosketa-poltsa',
      'bolsa da compra',
      'sac de courses',
      'Einkaufstasche',
    ),
  ]),
}
// cspell:enable

const labelsByTheme: ReadonlyMap<ThemeId, ReadonlySet<string>> = new Map(
  themes.map(
    (theme) =>
      [
        theme.id,
        new Set([
          ...theme.places,
          ...theme.items.map(({ label }) => label),
          ...(theme.roomObjects ?? []).map(({ label }) => label),
        ]),
      ] as const,
  ),
)

export const localizeThemeLabel = (
  locale: Locale,
  themeId: ThemeId,
  sourceLabel: string,
): string => {
  if (!labelsByTheme.get(themeId)?.has(sourceLabel)) return sourceLabel

  const translation = themeOverrides[themeId]?.get(sourceLabel) ?? translations.get(sourceLabel)
  if (!translation) throw new Error(`Etiqueta de tema sense traducció: ${sourceLabel}`)

  return translation[locale]
}

export const localizeThemePositionLabel = (
  locale: Locale,
  themeId: ThemeId,
  sourceLabel: string,
): string => {
  const match = /^(.*?)(\s·\s\d+(?:\.\d+)?)$/u.exec(sourceLabel)
  if (!match) {
    const cubeParts = sourceLabel.split(' · ')
    return cubeParts.length === 2
      ? cubeParts.map((part) => localizeThemeLabel(locale, themeId, part)).join(' · ')
      : localizeThemeLabel(locale, themeId, sourceLabel)
  }
  return `${localizeThemeLabel(locale, themeId, match[1])}${match[2]}`
}
