import { themes } from './themes'
import type { Locale, ThemeId } from './types'

// cspell:words pérgola
type LabelTranslation = readonly [es: string, en: string]

const translations: ReadonlyMap<string, LabelTranslation> = new Map<string, LabelTranslation>([
  ['La clariana', ['El claro', 'The clearing']],
  ['L’arbre gran', ['El árbol grande', 'The big tree']],
  ['El pont de fusta', ['El puente de madera', 'The wooden bridge']],
  ['El jardí de flors', ['El jardín de flores', 'The flower garden']],
  ['La cabana', ['La cabaña', 'The cabin']],
  ['El rierol', ['El arroyo', 'The stream']],
  ['La roca rodona', ['La roca redonda', 'The round rock']],
  ['La praderia', ['La pradera', 'The meadow']],
  ['galeta', ['galleta', 'cookie']],
  ['flor', ['flor', 'flower']],
  ['globus', ['globo', 'balloon']],
  ['barret', ['sombrero', 'hat']],
  ['poma', ['manzana', 'apple']],
  ['llibre', ['libro', 'book']],
  ['estrella', ['estrella', 'star']],
  ['fulla', ['hoja', 'leaf']],

  ['La platja suau', ['La playa tranquila', 'The calm beach']],
  ['La palmera', ['La palmera', 'The palm tree']],
  ['La cova de petxines', ['La cueva de conchas', 'The seashell cave']],
  ['El far', ['El faro', 'The lighthouse']],
  ['El moll', ['El muelle', 'The pier']],
  ['La duna daurada', ['La duna dorada', 'The golden dune']],
  ['La llacuna', ['La laguna', 'The lagoon']],
  ['El mirador', ['El mirador', 'The lookout']],
  ['petxina', ['concha', 'seashell']],
  ['mapa', ['mapa', 'map']],
  ['pinya', ['piña', 'pineapple']],
  ['banderí', ['banderín', 'pennant']],
  ['sol', ['sol', 'sun']],
  ['cubell', ['cubo', 'bucket']],
  ['corall', ['coral', 'coral']],
  ['barqueta', ['bote pequeño', 'little boat']],

  ['La biblioteca', ['La biblioteca', 'The library']],
  ['L’aula d’estrelles', ['El aula de estrellas', 'The star classroom']],
  ['El pati', ['El patio', 'The courtyard']],
  ['La torre', ['La torre', 'The tower']],
  ['El taller', ['El taller', 'The workshop']],
  ['L’hivernacle', ['El invernadero', 'The greenhouse']],
  ['La sala de música', ['La sala de música', 'The music room']],
  ['El passadís arc de Sant Martí', ['El pasillo arcoíris', 'The rainbow hallway']],
  ['vareta de flors', ['varita de flores', 'flower wand']],
  ['poció de bombolles', ['poción de burbujas', 'bubble potion']],
  ['llibre de contes', ['libro de cuentos', 'storybook']],
  ['capa', ['capa', 'cape']],
  ['clau daurada', ['llave dorada', 'golden key']],
  ['ploma', ['pluma', 'feather']],
  ['cristall', ['cristal', 'crystal']],

  ['El planeta blau', ['El planeta azul', 'The blue planet']],
  ['L’estació musical', ['La estación musical', 'The music station']],
  ['La lluna petita', ['La luna pequeña', 'The small moon']],
  ['El jardí estel·lar', ['El jardín estelar', 'The star garden']],
  ['El coet', ['El cohete', 'The rocket']],
  ['L’observatori', ['El observatorio', 'The observatory']],
  ['El núvol còsmic', ['La nube cósmica', 'The cosmic cloud']],
  ['L’anella brillant', ['El anillo brillante', 'The bright ring']],
  ['coet petit', ['cohete pequeño', 'small rocket']],
  ['planeta', ['planeta', 'planet']],
  ['satèl·lit', ['satélite', 'satellite']],
  ['flor lunar', ['flor lunar', 'moon flower']],
  ['comandament', ['mando', 'controller']],
  ['cometa', ['cometa', 'comet']],
  ['auriculars', ['auriculares', 'headphones']],

  ['L’hort', ['El huerto', 'The vegetable garden']],
  ['El paller', ['El pajar', 'The hayloft']],
  ['L’estable', ['El establo', 'The stable']],
  ['El pomer', ['El manzano', 'The apple tree']],
  ['La bassa', ['El estanque', 'The pond']],
  ['El molí', ['El molino', 'The mill']],
  ['La tanca blava', ['La valla azul', 'The blue fence']],
  ['La caseta', ['La casita', 'The little shed']],
  ['pastanaga', ['zanahoria', 'carrot']],
  ['blat', ['trigo', 'wheat']],
  ['llet', ['leche', 'milk']],
  ['regadora', ['regadera', 'watering can']],
  ['cistell', ['cesto', 'basket']],
  ['campaneta', ['campanilla', 'small bell']],

  ['El corall rosa', ['El coral rosa', 'The pink coral']],
  ['La cova blava', ['La cueva azul', 'The blue cave']],
  ['L’alguer', ['El campo de algas', 'The seaweed bed']],
  ['La petxina gran', ['La concha grande', 'The big seashell']],
  ['La roca cantant', ['La roca cantora', 'The singing rock']],
  ['El jardí de perles', ['El jardín de perlas', 'The pearl garden']],
  ['La bombolla gegant', ['La burbuja gigante', 'The giant bubble']],
  ['El sorral', ['El arenal', 'The sandy patch']],
  ['perla', ['perla', 'pearl']],
  ['alga', ['alga', 'seaweed']],
  ['estrella marina', ['estrella de mar', 'starfish']],
  ['peixet', ['pez pequeño', 'little fish']],
  ['bombolla', ['burbuja', 'bubble']],
  ['corona', ['corona', 'crown']],

  ['El niu de fulles', ['El nido de hojas', 'The leaf nest']],
  ['El llac', ['El lago', 'The lake']],
  ['La roca alta', ['La roca alta', 'The tall rock']],
  ['El bosc de falgueres', ['El bosque de helechos', 'The fern forest']],
  ['La vall', ['El valle', 'The valley']],
  ['El pont', ['El puente', 'The bridge']],
  ['La font', ['La fuente', 'The fountain']],
  ['El turó', ['La colina', 'The hill']],
  ['petjada', ['huella', 'footprint']],
  ['motxilla', ['mochila', 'backpack']],
  ['prismàtics', ['prismáticos', 'binoculars']],
  ['pedreta', ['piedra pequeña', 'pebble']],

  ['La plaça', ['La plaza', 'The town square']],
  ['La fleca', ['La panadería', 'The bakery']],
  ['El cinema', ['El cine', 'The cinema']],
  ['El jardí', ['El jardín', 'The garden']],
  ['La caseta groga', ['La casita amarilla', 'The little yellow house']],
  ['pastís', ['pastel', 'cake']],
  ['pintura', ['pintura', 'paint']],
  ['música', ['música', 'music']],

  ['La roda de colors', ['La rueda de colores', 'The color wheel']],
  ['La parada groga', ['El puesto amarillo', 'The yellow stall']],
  ['El teatre', ['El teatro', 'The theater']],
  ['El jardí de globus', ['El jardín de globos', 'The balloon garden']],
  ['La carpa', ['La carpa', 'The big top']],
  ['El carrusel', ['El carrusel', 'The carousel']],
  ['El racó de contes', ['El rincón de cuentos', 'The story corner']],
  ['La fonteta', ['La fuente pequeña', 'The small fountain']],
  ['entrada', ['entrada', 'ticket']],
  ['pinzell', ['pincel', 'paintbrush']],
  ['cor', ['corazón', 'heart']],
  ['cinta', ['cinta', 'ribbon']],
  ['conte', ['cuento', 'story']],

  ['El refugi', ['El refugio', 'The shelter']],
  ['El prat', ['El prado', 'The meadow']],
  ['La cascada suau', ['La cascada tranquila', 'The gentle waterfall']],
  ['El bosc', ['El bosque', 'The forest']],
  ['El pontet', ['El puente pequeño', 'The small bridge']],
  ['La cova de colors', ['La cueva de colores', 'The colorful cave']],
  ['El cim', ['La cima', 'The summit']],
  ['cantimplora', ['cantimplora', 'water bottle']],

  ['La cabina 1', ['La cabina 1', 'Booth 1']],
  ['La cabina 2', ['La cabina 2', 'Booth 2']],
  ['La taula de mescles', ['La mesa de mezclas', 'The mixing desk']],
  ['El teclat', ['El teclado', 'The keyboard']],
  ['El mural de pòsters', ['El mural de pósteres', 'The poster wall']],
  ['La sala d’assaig', ['La sala de ensayo', 'The rehearsal room']],
  ['El racó del baix', ['El rincón del bajo', 'The bass corner']],
  ['El sofà blau', ['El sofá azul', 'The blue sofa']],
  ['acreditació', ['acreditación', 'pass']],
  ['mòbil', ['móvil', 'phone']],
  ['gorra', ['gorra', 'cap']],
  ['jaqueta', ['chaqueta', 'jacket']],
  ['ulleres', ['gafas', 'glasses']],
  ['rellotge', ['reloj', 'watch']],
  ['carpeta', ['carpeta', 'folder']],
  ['micròfon de peu', ['micrófono de pie', 'stand microphone']],
  ['mesclador', ['mezclador', 'mixer']],
  ['taula de control', ['mesa de control', 'control desk']],
  ['altaveu', ['altavoz', 'speaker']],
  ['teclat', ['teclado', 'keyboard']],
  ['tambor', ['tambor', 'drum']],
  ['guitarra', ['guitarra', 'guitar']],
  ['saxòfon', ['saxofón', 'saxophone']],
  ['violí', ['violín', 'violin']],
  ['cadira', ['silla', 'chair']],
  ['llum de taula', ['lámpara de mesa', 'table lamp']],
  ['armari', ['armario', 'cabinet']],
  ['caixa d’eines', ['caja de herramientas', 'toolbox']],
  ['bloc de notes', ['bloc de notas', 'notepad']],
  ['partitura', ['partitura', 'sheet music']],
  ['ordinador', ['ordenador', 'computer']],
  ['temporitzador', ['temporizador', 'timer']],
  ['endoll', ['enchufe', 'power socket']],
  ['got d’aigua', ['vaso de agua', 'glass of water']],

  ['La pista verda', ['La pista verde', 'The green court']],
  ['La pista blava', ['La pista azul', 'The blue court']],
  ['El mur d’escalada', ['El muro de escalada', 'The climbing wall']],
  ['La zona d’estiraments', ['La zona de estiramientos', 'The stretching area']],
  ['La taula de marques', ['La mesa de marcas', 'The score table']],
  ['El circuit', ['El circuito', 'The course']],
  ['La grada', ['La grada', 'The bleachers']],
  ['El punt d’aigua', ['El punto de agua', 'The water point']],
  ['dorsal', ['dorsal', 'bib']],
  ['casc', ['casco', 'helmet']],
  ['mocador', ['pañuelo', 'scarf']],
  ['sabatilles', ['zapatillas', 'trainers']],
  ['pilota de bàsquet', ['balón de baloncesto', 'basketball']],
  ['pilota de futbol', ['balón de fútbol', 'football']],
  ['pilota de voleibol', ['balón de voleibol', 'volleyball']],
  ['disc', ['disco volador', 'flying disc']],
  ['raqueta de taula', ['pala de tenis de mesa', 'table tennis paddle']],
  ['porteria', ['portería', 'goal']],
  ['patí', ['monopatín', 'skateboard']],
  ['bicicleta', ['bicicleta', 'bicycle']],
  ['banc', ['banco', 'bench']],
  ['font d’aigua', ['fuente de agua', 'water fountain']],
  ['cronòmetre', ['cronómetro', 'stopwatch']],
  ['megàfon', ['megáfono', 'megaphone']],
  ['samarreta', ['camiseta', 'shirt']],
  ['cistella', ['cesta', 'basket']],
  ['ampolla', ['botella', 'bottle']],
  ['bossa d’equip', ['bolsa de equipo', 'kit bag']],
  ['escala', ['escalera', 'ladder']],
  ['trofeu', ['trofeo', 'trophy']],
  ['medalla', ['medalla', 'medal']],

  ['La taula de disseny', ['La mesa de diseño', 'The design table']],
  ['La paret d’idees', ['La pared de ideas', 'The ideas wall']],
  ['L’estació de color', ['La estación de color', 'The color station']],
  ['El racó de vídeo', ['El rincón de vídeo', 'The video corner']],
  ['La impressora', ['La impresora', 'The printer']],
  ['La taula de maquetes', ['La mesa de maquetas', 'The model table']],
  ['El sofà de prova', ['El sofá de prueba', 'The testing sofa']],
  ['La finestra gran', ['La ventana grande', 'The large window']],
  ['llapis', ['lápiz', 'pencil']],
  ['goma', ['goma', 'eraser']],
  ['portafolis', ['portafolios', 'portfolio']],
  ['retolador', ['rotulador', 'marker']],
  ['pantalla', ['pantalla', 'screen']],
  ['impressora', ['impresora', 'printer']],
  ['càmera', ['cámara', 'camera']],
  ['llum de treball', ['lámpara de trabajo', 'work lamp']],
  ['escaire', ['escuadra', 'set square']],
  ['regle', ['regla', 'ruler']],
  ['paleta de color', ['paleta de color', 'color palette']],
  ['rodet de fil', ['carrete de hilo', 'thread spool']],
  ['cabdell', ['ovillo', 'ball of yarn']],
  ['xinxeta', ['chincheta', 'pushpin']],
  ['llibres', ['libros', 'books']],
  ['bloc d’esbossos', ['bloc de bocetos', 'sketchbook']],
  ['marc', ['marco', 'frame']],
  ['maqueta', ['maqueta', 'model']],
  ['portàtil', ['portátil', 'laptop']],
  ['mirall', ['espejo', 'mirror']],
  ['caixa', ['caja', 'box']],

  ['La taula rodona', ['La mesa redonda', 'The round table']],
  ['La butaca verda', ['El sillón verde', 'The green armchair']],
  ['El finestral', ['El ventanal', 'The picture window']],
  ['La prestatgeria', ['La estantería', 'The bookshelf']],
  ['La taula petita', ['La mesa pequeña', 'The small table']],
  ['El racó tranquil', ['El rincón tranquilo', 'The quiet corner']],
  ['La llum de peu', ['La lámpara de pie', 'The floor lamp']],
  ['La cafetera', ['La cafetera', 'The coffee maker']],
  ['novel·la', ['novela', 'novel']],
  ['punt de llibre', ['marcador de lectura', 'bookmark']],
  ['quadern', ['cuaderno', 'notebook']],
  ['fullet', ['folleto', 'leaflet']],
  ['bossa', ['bolso', 'bag']],
  ['sofà', ['sofá', 'sofa']],
  ['planta', ['planta', 'plant']],
  ['llum de lectura', ['lámpara de lectura', 'reading lamp']],
  ['tassa', ['taza', 'mug']],
  ['tetera', ['tetera', 'teapot']],
  ['diari', ['periódico', 'newspaper']],
  ['quadre', ['cuadro', 'picture']],
  ['revister', ['revistero', 'magazine rack']],
  ['llibre obert', ['libro abierto', 'open book']],
  ['finestra', ['ventana', 'window']],
  ['porta', ['puerta', 'door']],
  ['paraigüer', ['soporte para paraguas', 'umbrella stand']],

  ['L’hort alt', ['El huerto elevado', 'The raised garden bed']],
  ['La taula de llavors', ['La mesa de semillas', 'The seed table']],
  ['El banc llarg', ['El banco largo', 'The long bench']],
  ['La pèrgola', ['La pérgola', 'The pergola']],
  ['La vora de la bassa', ['El borde del estanque', 'The pond edge']],
  ['El compostador', ['El compostador', 'The compost bin']],
  ['La taula d’eines', ['La mesa de herramientas', 'The tool table']],
  ['La porta blava', ['La puerta azul', 'The blue door']],
  ['guants', ['guantes', 'gloves']],
  ['botes', ['botes', 'boots']],
  ['etiqueta', ['etiqueta', 'label']],
  ['llibreta', ['libreta', 'notebook']],
  ['cordill', ['cordel', 'string']],
  ['pinça', ['pinza', 'clip']],
  ['test', ['maceta', 'plant pot']],
  ['galleda', ['cubo', 'bucket']],
  ['tanca baixa', ['valla baja', 'low fence']],
  ['fusta', ['madera', 'wood']],
  ['pedra', ['piedra', 'stone']],
  ['planter', ['semillero', 'seed tray']],
  ['cartell', ['cartel', 'sign']],
  ['aixeta', ['grifo', 'tap']],
  ['carretó', ['carretilla', 'wheelbarrow']],
  ['gira-sol', ['girasol', 'sunflower']],
  ['tomàquet', ['tomate', 'tomato']],
  ['pèsols', ['guisantes', 'peas']],
  ['maó', ['ladrillo', 'brick']],
  ['escombra', ['escoba', 'broom']],
  ['esponja', ['esponja', 'sponge']],
  ['gerro', ['jarrón', 'vase']],
  ['nenúfar', ['nenúfar', 'water lily']],
  ['gota d’aigua', ['gota de agua', 'water drop']],
  ['granota', ['rana', 'frog']],
  ['ànec', ['pato', 'duck']],
  ['fulles seques', ['hojas secas', 'dry leaves']],
  ['cuc de terra', ['lombriz', 'earthworm']],

  ['La parada de pa', ['El puesto de pan', 'The bread stall']],
  ['La parada de fruita', ['El puesto de fruta', 'The fruit stall']],
  ['La parada de flors', ['El puesto de flores', 'The flower stall']],
  ['La parada de cafè', ['El puesto de café', 'The coffee stall']],
  ['La parada de ceràmica', ['El puesto de cerámica', 'The pottery stall']],
  ['La parada de formatges', ['El puesto de quesos', 'The cheese stall']],
  ['La taula central', ['La mesa central', 'The central table']],
  ['L’entrada', ['La entrada', 'The entrance']],
  ['llista', ['lista', 'list']],
  ['moneder', ['monedero', 'wallet']],
  ['targeta', ['tarjeta', 'card']],
  ['paraigua', ['paraguas', 'umbrella']],
  ['clauer', ['llavero', 'key ring']],
  ['balança', ['balanza', 'scales']],
  ['rebut', ['recibo', 'receipt']],
  ['formatge', ['queso', 'cheese']],
  ['pa', ['pan', 'bread']],
  ['ram', ['ramo', 'bouquet']],
  ['pot', ['tarro', 'jar']],
  ['pera', ['pera', 'pear']],
])

const themeOverrides: Readonly<
  Partial<Record<ThemeId, ReadonlyMap<string, LabelTranslation>>>
> = {
  'book-club': new Map<string, LabelTranslation>([
    ['ploma', ['estilográfica', 'fountain pen']],
    ['rellotge', ['reloj', 'clock']],
  ]),
}

const labelsByTheme: ReadonlyMap<ThemeId, ReadonlySet<string>> = new Map(
  themes.map(
    (theme) =>
      [
        theme.id,
        new Set([
          ...theme.places,
          ...theme.items.map(({ label }) => label),
          ...(theme.roomObjects ?? []).map(({ label }) => label),
        ]),
      ] as const,
  ),
)

export const localizeThemeLabel = (
  locale: Locale,
  themeId: ThemeId,
  sourceLabel: string,
): string => {
  if (locale === 'ca' || !labelsByTheme.get(themeId)?.has(sourceLabel)) return sourceLabel

  const translation = themeOverrides[themeId]?.get(sourceLabel) ?? translations.get(sourceLabel)
  if (!translation) return sourceLabel

  return locale === 'es' ? translation[0] : translation[1]
}

export const localizeThemePositionLabel = (
  locale: Locale,
  themeId: ThemeId,
  sourceLabel: string,
): string => {
  const match = /^(.*?)(\s·\s\d+(?:\.\d+)?)$/u.exec(sourceLabel)
  if (!match) {
    const cubeParts = sourceLabel.split(' · ')
    return cubeParts.length === 2
      ? cubeParts.map((part) => localizeThemeLabel(locale, themeId, part)).join(' · ')
      : localizeThemeLabel(locale, themeId, sourceLabel)
  }
  return `${localizeThemeLabel(locale, themeId, match[1])}${match[2]}`
}
