import {
  AudioWaveform,
  Bolt,
  CircleDot,
  Diamond,
  Disc3,
  Droplets,
  Flower2,
  Gem,
  Hexagon,
  Leaf,
  Music2,
  Shell,
  Shapes,
  Sparkles,
  Sprout,
  Waves,
  type LucideIcon,
} from 'lucide-react'
import type { MotifId } from './floorDecorations'

export const floorMotifIcons: Readonly<Record<MotifId, LucideIcon>> = {
  audio: AudioWaveform,
  bolt: Bolt,
  circle: CircleDot,
  diamond: Diamond,
  disc: Disc3,
  droplets: Droplets,
  flower: Flower2,
  gem: Gem,
  hexagon: Hexagon,
  leaf: Leaf,
  music: Music2,
  shell: Shell,
  shapes: Shapes,
  sparkles: Sparkles,
  sprout: Sprout,
  waves: Waves,
}
